// Package natsauth centralizes PeerGo's mounted NATS credential handling.
// Cluster deployments continue to use ordinary NATS JWT .creds files. The
// explicitly selected single-server profile may instead mount the compact
// username/password format generated by PeerGo's bootstrap script.
package natsauth

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/nats-io/nats.go"
)

const SingleServerMarker = "peergo-single-server-user-password-v1"

// OptionFromCredentialsFile returns one NATS authentication option for either
// a standard NATS JWT credential file or PeerGo's single-server secret file.
// Reading the file here makes missing mounts fail before a connection attempt.
func OptionFromCredentialsFile(path string) (nats.Option, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read NATS credentials: %w", err)
	}
	if len(contents) > 64<<10 {
		return nil, errors.New("NATS credentials file exceeds 64 KiB")
	}
	firstLine := strings.TrimSuffix(strings.SplitN(string(contents), "\n", 2)[0], "\r")
	if firstLine != SingleServerMarker {
		return nats.UserCredentials(path), nil
	}

	values := make(map[string]string, 2)
	scanner := bufio.NewScanner(strings.NewReader(string(contents)))
	line := 0
	for scanner.Scan() {
		line++
		if line == 1 {
			continue
		}
		text := strings.TrimSpace(scanner.Text())
		if text == "" {
			continue
		}
		key, value, found := strings.Cut(text, "=")
		if !found || (key != "username" && key != "password") || strings.TrimSpace(value) == "" {
			return nil, fmt.Errorf("invalid PeerGo single-server NATS credential line %d", line)
		}
		if _, duplicate := values[key]; duplicate {
			return nil, fmt.Errorf("duplicate %s in PeerGo single-server NATS credentials", key)
		}
		values[key] = strings.TrimSpace(value)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan NATS credentials: %w", err)
	}
	if values["username"] == "" || values["password"] == "" {
		return nil, errors.New("PeerGo single-server NATS credentials require username and password")
	}
	return nats.UserInfo(values["username"], values["password"]), nil
}
