.PHONY: generate format test check test-e2e release-check dev-web dev-core dev-core-watch dev-worker dev-image-derivative-worker dev-image-derivative-worker-watch dev-promotion-worker dev-promotion-worker-watch dev-settlement-control-worker dev-settlement-control-worker-watch dev-seeding-reward-worker dev-seeding-reward-worker-watch dev-contribution-experience-worker dev-contribution-experience-worker-watch dev-progression-level-worker dev-progression-level-worker-watch dev-projector dev-snapshot-builder dev-snapshot-publisher dev-core-traffic-consumer dev-core-traffic-projector dev-core-seeding-evidence-consumer dev-core-seeding-evidence-projector dev-core-hnr-consumer dev-core-hnr-projector dev-core-swarm-consumers dev-core-swarm-projector tracker-snapshot-inspect dev-tracker-stream dev-tracker-swarm-stream dev-tracker dev-settlement-consumer dev-settlement dev-settlement-policy dev-settlement-seeding-snapshot-consumer dev-settlement-seeding-snapshot-projector dev-settlement-seeding-evidence-worker dev-settlement-seeding-evidence-stream dev-settlement-seeding-evidence-dispatcher dev-settlement-promotion-control dev-settlement-promotion-control-watch dev-settlement-policy-timeline dev-settlement-traffic-stream dev-settlement-traffic-dispatcher dev-settlement-hnr-policy-timeline dev-settlement-hnr-worker dev-settlement-hnr-stream dev-settlement-hnr-dispatcher dev-traffic-demo dev-vault dev-audit dev-object-storage dev-torrent-storage dev-torrent-upload-reconcile admin admin-revoke staff-bootstrap compose-up compose-down db-migrate db-status db-seed
.PHONY: legacy-migrate rousi-restore-local rousi-restore-production-prepare rousi-restore-production-apply rousi-restore-production-status single-server-bootstrap production-config production-ready production-build production-up production-down production-status production-activation-check production-policy-bootstrap production-admin production-admin-revoke

# These values are synthetic and limited to the loopback-only local Compose
# environment. Production processes require explicit secret-backed variables.
CORE_DATABASE_URL ?= postgres://peergo_core:peergo_local_only@127.0.0.1:5432/peergo_core?sslmode=disable
VAULT_DATABASE_URL ?= postgres://peergo_vault:peergo_vault_local_only@127.0.0.1:5433/peergo_vault?sslmode=disable
TRACKER_DATABASE_URL ?= postgres://peergo_tracker:peergo_tracker_local_only@127.0.0.1:5434/peergo_tracker?sslmode=disable
LOCAL_VAULT_IDENTIFIER_KEY ?= peergo-local-identifier-key-v1-2026
LOCAL_VAULT_TOTP_ENCRYPTION_KEY ?= 0123456789abcdef0123456789abcdef
LOCAL_VAULT_TOTP_KEY_EPOCH ?= local-2026-08
LOCAL_VAULT_TRACKER_PASSKEY_ENCRYPTION_KEY ?= abcdef0123456789abcdef0123456789
LOCAL_VAULT_TRACKER_PASSKEY_KEY_EPOCH ?= local-2026-08
LOCAL_TRACKER_PASSKEY_LOOKUP_KEY ?= peergo-local-tracker-passkey-lookup-key-v1-2026
LOCAL_VAULT_SERVICE_TOKEN ?= peergo-local-vault-service-token-v1-2026
LOCAL_TRACKER_SERVICE_TOKEN ?= peergo-local-tracker-service-token-v1-2026
LOCAL_EMAIL_VERIFICATION_PUBLIC_URL ?= http://localhost:5173/verify-email
LOCAL_PASSWORD_RECOVERY_PUBLIC_URL ?= http://localhost:5173/reset-password
LOCAL_EMAIL_OUTBOX_PATH ?= $(CURDIR)/.local/mail/messages.jsonl
LOCAL_SESSION_CSRF_KEY ?= peergo-local-session-csrf-key-v1-2026
LOCAL_WEBAUTHN_RECORD_KEY ?= 0123456789abcdef0123456789abcdef
LOCAL_WEBAUTHN_KEY_EPOCH ?= local-2026-08
LOCAL_WEBAUTHN_RP_ID ?= localhost
LOCAL_WEBAUTHN_ORIGINS ?= http://localhost:5173,http://localhost:5174,http://localhost:4173
LOCAL_AUDIT_PSEUDONYM_KEY ?= peergo-local-audit-pseudonym-key-v1-2026
LOCAL_AUDIT_PSEUDONYM_KEY_EPOCH ?= local-2026-08
LOCAL_AUDIT_SERVICE_TOKEN ?= peergo-local-audit-service-token-v1-2026
LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN ?= peergo-local-settlement-control-token-v1-2026
LOCAL_SETTLEMENT_CONTROL_URL ?= http://127.0.0.1:8085
LOCAL_TORRENT_OBJECT_ROOT ?= $(CURDIR)/.local/objects
LOCAL_IMAGE_DERIVATIVE_TEMP_ROOT ?= $(CURDIR)/.local/image-derivatives
LOCAL_TRACKER_SNAPSHOT_KEY_ID ?= local-2026-08
# RFC 8032 test-vector material: development only, never a production key.
LOCAL_TRACKER_SNAPSHOT_SIGNING_SEED_BASE64 ?= nWGxne/9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A=
LOCAL_TRACKER_SNAPSHOT_PUBLIC_KEY_BASE64 ?= 11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo=
LOCAL_TRACKER_SNAPSHOT_PATH ?= $(CURDIR)/.local/tracker/control.snapshot
LOCAL_TRACKER_SUBJECT_SNAPSHOT_PATH ?= $(CURDIR)/.local/tracker/subjects.snapshot
LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH ?= $(CURDIR)/.local/tracker/runtime-policy.snapshot
LOCAL_TRACKER_SNAPSHOT_MAX_AGE ?= 15m
LOCAL_TRACKER_SUBJECT_SNAPSHOT_MAX_AGE ?= 1m
LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_MAX_AGE ?= 15m
LOCAL_TRACKER_SNAPSHOT_MAX_FUTURE_SKEW ?= 2m
LOCAL_TRACKER_CANONICAL_ORIGIN ?= http://127.0.0.1:8083
LOCAL_TRACKER_LISTEN_ADDRESS ?= 127.0.0.1:8083
LOCAL_TRACKER_METRICS_LISTEN_ADDRESS ?= 127.0.0.1:9093
LOCAL_TRACKER_WAL_PATH ?= $(CURDIR)/.local/tracker/announce.wal
LOCAL_TRACKER_SWARM_SEQUENCE_PATH ?= $(CURDIR)/.local/tracker/swarm-sequence.json
LOCAL_TRACKER_NATS_URLS ?= nats://127.0.0.1:4222
LOCAL_TRACKER_ANNOUNCE_STREAM ?= PEERGO_TRACKER_ANNOUNCE_V1
LOCAL_TRACKER_ANNOUNCE_SUBJECT ?= peergo.tracker.announce.v1
LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM ?= PEERGO_TRACKER_SWARM_SNAPSHOT_V1
LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT ?= peergo.tracker.swarm.snapshot.v1
LOCAL_TRACKER_SWARM_SOURCE_ID ?= tracker-primary
LOCAL_TRACKER_SWARM_ROUTING_EPOCH ?= 1
LOCAL_SETTLEMENT_ANNOUNCE_DURABLE ?= PEERGO_SETTLEMENT_V1
LOCAL_SETTLEMENT_SEEDING_SNAPSHOT_DURABLE ?= PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_V1
LOCAL_SETTLEMENT_SEEDING_EVIDENCE_START_AT ?= 2026-08-15T00:00:00Z
LOCAL_SETTLEMENT_TRAFFIC_STREAM ?= PEERGO_SETTLEMENT_TRAFFIC_V1
LOCAL_SETTLEMENT_TRAFFIC_SUBJECT ?= peergo.settlement.traffic.v1
LOCAL_SETTLEMENT_SEEDING_EVIDENCE_STREAM ?= PEERGO_SETTLEMENT_SEEDING_EVIDENCE_V1
LOCAL_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT ?= peergo.settlement.seeding.evidence.v1
LOCAL_SETTLEMENT_HNR_STREAM ?= PEERGO_SETTLEMENT_HNR_V1
LOCAL_SETTLEMENT_HNR_SUBJECT ?= peergo.settlement.hnr.v1
LOCAL_CORE_TRAFFIC_DURABLE ?= PEERGO_CORE_TRAFFIC_V1
LOCAL_CORE_SEEDING_EVIDENCE_DURABLE ?= PEERGO_CORE_SEEDING_EVIDENCE_V1
LOCAL_CORE_HNR_DURABLE ?= PEERGO_CORE_HNR_V1
LOCAL_CORE_SWARM_SNAPSHOT_DURABLE ?= PEERGO_CORE_SWARM_SNAPSHOT_V1
LOCAL_CORE_SWARM_COMPLETION_DURABLE ?= PEERGO_CORE_SWARM_COMPLETION_V1
AUDIT_SINK_URL ?= http://127.0.0.1:8082
AUDIT_JOURNAL_PATH ?= $(CURDIR)/.local/audit/events.jsonl
DEMO_PASSWORD ?= PeerGo-demo-2026!
WEB_ORIGINS ?= http://127.0.0.1:5173,http://localhost:5173,http://127.0.0.1:5174,http://localhost:5174,http://10.10.10.23:5174,http://127.0.0.1:4173,http://localhost:4173
LOCAL_PUBLIC_ORIGIN ?= http://10.10.10.23:5174
LOCAL_TURNSTILE_SECRET_KEY ?=

generate:
	pnpm contract:bundle
	pnpm --filter @peergo/web generate:api
	GOWORK=off go -C services/core generate ./...
	GOWORK=off go -C tools/devtools tool sqlc -f ../../services/core/sqlc.yaml generate
	GOWORK=off go -C tools/devtools tool sqlc -f ../../services/privacy-vault/sqlc.yaml generate
	GOWORK=off go -C tools/devtools tool sqlc -f ../../services/settlement/sqlc.yaml generate

format:
	pnpm --filter @peergo/web format
	GOWORK=off go -C contracts/go fmt ./...
	GOWORK=off go -C libraries/natsauth fmt ./...
	GOWORK=off go -C services/core fmt ./...
	GOWORK=off go -C services/privacy-vault fmt ./...
	GOWORK=off go -C services/email-relay fmt ./...
	GOWORK=off go -C services/audit-sink fmt ./...
	GOWORK=off go -C services/settlement fmt ./...
	GOWORK=off go -C services/tracker fmt ./...
	GOWORK=off go -C tools/traffic-corpus fmt ./...

test:
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest scripts/test_bootstrap_production_policies.py
	pnpm test:web
	GOWORK=off go -C contracts/go test ./...
	GOWORK=off go -C libraries/natsauth test ./...
	GOWORK=off go -C services/core test ./...
	GOWORK=off go -C services/privacy-vault test ./...
	GOWORK=off go -C services/email-relay test ./...
	GOWORK=off go -C services/audit-sink test ./...
	GOWORK=off go -C services/settlement test ./...
	GOWORK=off go -C services/tracker test ./...
	GOWORK=off go -C tools/traffic-corpus test ./...

check: generate
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest scripts/test_bootstrap_production_policies.py
	pnpm contract:lint
	pnpm typecheck:web
	pnpm --filter @peergo/web format:check
	pnpm test:web
	pnpm build:web
	GOWORK=off go -C contracts/go test ./...
	GOWORK=off go -C libraries/natsauth test ./...
	GOWORK=off go -C services/core test ./...
	GOWORK=off go -C services/privacy-vault test ./...
	GOWORK=off go -C services/email-relay test ./...
	GOWORK=off go -C services/audit-sink test ./...
	GOWORK=off go -C services/settlement test ./...
	GOWORK=off go -C services/tracker test ./...
	GOWORK=off go -C tools/traffic-corpus test ./...

test-e2e:
	pnpm test:e2e:web

release-check: check test-e2e

legacy-migrate:
	./scripts/migrate-ptyes.sh $(ARGS)

# Destructive loopback-only rehearsal. The confirmation value is deliberately
# explicit; the script saves recoverable local database/object backups before
# replacing the PeerGo development volumes with the three Rousi snapshots.
rousi-restore-local:
	PEERGO_LOCAL_RESTORE_CONFIRM="$(CONFIRM_ROUSI_LOCAL_RESET)" \
		./scripts/restore-rousi-local.sh \
		"$(ROUSI_DUMP)" "$(ROUSI_TORRENTS)" "$(ROUSI_UPLOADS)"

# Formal production cutover uses the same three immutable inputs as the local
# rehearsal, but never resets a target or automatically approves a physically
# missing .torrent. Prepare is source-only; apply requires an exact candidate
# digest whenever prepare emitted one.
rousi-restore-production-prepare:
	PEERGO_PRODUCTION_RESTORE_CONFIRM="$(CONFIRM_ROUSI_PRODUCTION)" \
	PEERGO_CUTOVER_BACKUP_REFERENCE="$(ROUSI_BACKUP_REFERENCE)" \
	PEERGO_CUTOVER_WRITES_STOPPED_AT="$(ROUSI_WRITES_STOPPED_AT)" \
		./scripts/restore-rousi-production.sh prepare \
		"$(ROUSI_DUMP)" "$(ROUSI_TORRENTS)" "$(ROUSI_UPLOADS)"

rousi-restore-production-apply:
	PEERGO_PRODUCTION_RESTORE_CONFIRM="$(CONFIRM_ROUSI_PRODUCTION)" \
	PEERGO_CUTOVER_BACKUP_REFERENCE="$(ROUSI_BACKUP_REFERENCE)" \
	PEERGO_CUTOVER_WRITES_STOPPED_AT="$(ROUSI_WRITES_STOPPED_AT)" \
	PEERGO_CUTOVER_OPERATOR_REFERENCE="$(ROUSI_OPERATOR_REFERENCE)" \
	PEERGO_ROUSI_MISSING_TORRENTS_APPROVAL="$(CONFIRM_ROUSI_MISSING_TORRENTS)" \
		./scripts/restore-rousi-production.sh apply \
		"$(ROUSI_DUMP)" "$(ROUSI_TORRENTS)" "$(ROUSI_UPLOADS)"

rousi-restore-production-status:
	./scripts/restore-rousi-production.sh status \
		"$(ROUSI_DUMP)" "$(ROUSI_TORRENTS)" "$(ROUSI_UPLOADS)"

# Idempotent first-host preparation. It creates dedicated PeerGo roles,
# databases, paths, secrets and a private Docker network without deleting data.
single-server-bootstrap:
	./scripts/bootstrap-single-server.sh

dev-web:
	pnpm dev:web

dev-vault:
	PEERGO_ENV=development \
	PEERGO_VAULT_DATABASE_URL="$(VAULT_DATABASE_URL)" \
	PEERGO_VAULT_IDENTIFIER_KEY="$(LOCAL_VAULT_IDENTIFIER_KEY)" \
	PEERGO_VAULT_TOTP_ENCRYPTION_KEY="$(LOCAL_VAULT_TOTP_ENCRYPTION_KEY)" \
	PEERGO_VAULT_TOTP_KEY_EPOCH="$(LOCAL_VAULT_TOTP_KEY_EPOCH)" \
	PEERGO_VAULT_TRACKER_PASSKEY_ENCRYPTION_KEY="$(LOCAL_VAULT_TRACKER_PASSKEY_ENCRYPTION_KEY)" \
	PEERGO_VAULT_TRACKER_PASSKEY_KEY_EPOCH="$(LOCAL_VAULT_TRACKER_PASSKEY_KEY_EPOCH)" \
	PEERGO_TRACKER_PASSKEY_LOOKUP_KEY="$(LOCAL_TRACKER_PASSKEY_LOOKUP_KEY)" \
	PEERGO_VAULT_SERVICE_TOKEN="$(LOCAL_VAULT_SERVICE_TOKEN)" \
	PEERGO_EMAIL_VERIFICATION_PUBLIC_URL="$(LOCAL_EMAIL_VERIFICATION_PUBLIC_URL)" \
	PEERGO_PASSWORD_RECOVERY_PUBLIC_URL="$(LOCAL_PASSWORD_RECOVERY_PUBLIC_URL)" \
	PEERGO_EMAIL_OUTBOX_PATH="$(LOCAL_EMAIL_OUTBOX_PATH)" \
	go run ./services/privacy-vault/cmd/api

dev-core:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_VAULT_URL="http://127.0.0.1:8081" \
	PEERGO_VAULT_SERVICE_TOKEN="$(LOCAL_VAULT_SERVICE_TOKEN)" \
	PEERGO_SESSION_CSRF_KEY="$(LOCAL_SESSION_CSRF_KEY)" \
	PEERGO_WEBAUTHN_RP_ID="$(LOCAL_WEBAUTHN_RP_ID)" \
	PEERGO_WEBAUTHN_ORIGINS="$(LOCAL_WEBAUTHN_ORIGINS)" \
	PEERGO_WEBAUTHN_RECORD_KEY="$(LOCAL_WEBAUTHN_RECORD_KEY)" \
	PEERGO_WEBAUTHN_KEY_EPOCH="$(LOCAL_WEBAUTHN_KEY_EPOCH)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	PEERGO_TORRENT_UPLOAD_MAX_BYTES="4194304" \
	PEERGO_TRACKER_CANONICAL_ORIGIN="$(LOCAL_TRACKER_CANONICAL_ORIGIN)" \
	PEERGO_TRACKER_SERVICE_TOKEN="$(LOCAL_TRACKER_SERVICE_TOKEN)" \
	PEERGO_SETTLEMENT_CONTROL_URL="$(LOCAL_SETTLEMENT_CONTROL_URL)" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_START_AT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_START_AT)" \
	PEERGO_AUDIT_PSEUDONYM_KEY="$(LOCAL_AUDIT_PSEUDONYM_KEY)" \
	PEERGO_AUDIT_PSEUDONYM_KEY_EPOCH="$(LOCAL_AUDIT_PSEUDONYM_KEY_EPOCH)" \
	PEERGO_COOKIE_SECURE=false \
	PEERGO_WEB_ORIGINS="$(WEB_ORIGINS)" \
	PEERGO_PUBLIC_ORIGIN="$(LOCAL_PUBLIC_ORIGIN)" \
	PEERGO_TURNSTILE_SECRET_KEY="$(LOCAL_TURNSTILE_SECRET_KEY)" \
	go run ./services/core/cmd/api

# Air is pinned in tools/devtools. It inherits the same development-only
# environment as dev-core and only rebuilds the Core API on relevant Go edits.
dev-core-watch:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_VAULT_URL="http://127.0.0.1:8081" \
	PEERGO_VAULT_SERVICE_TOKEN="$(LOCAL_VAULT_SERVICE_TOKEN)" \
	PEERGO_SESSION_CSRF_KEY="$(LOCAL_SESSION_CSRF_KEY)" \
	PEERGO_WEBAUTHN_RP_ID="$(LOCAL_WEBAUTHN_RP_ID)" \
	PEERGO_WEBAUTHN_ORIGINS="$(LOCAL_WEBAUTHN_ORIGINS)" \
	PEERGO_WEBAUTHN_RECORD_KEY="$(LOCAL_WEBAUTHN_RECORD_KEY)" \
	PEERGO_WEBAUTHN_KEY_EPOCH="$(LOCAL_WEBAUTHN_KEY_EPOCH)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	PEERGO_TORRENT_UPLOAD_MAX_BYTES="4194304" \
	PEERGO_TRACKER_CANONICAL_ORIGIN="$(LOCAL_TRACKER_CANONICAL_ORIGIN)" \
	PEERGO_TRACKER_SERVICE_TOKEN="$(LOCAL_TRACKER_SERVICE_TOKEN)" \
	PEERGO_SETTLEMENT_CONTROL_URL="$(LOCAL_SETTLEMENT_CONTROL_URL)" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_START_AT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_START_AT)" \
	PEERGO_AUDIT_PSEUDONYM_KEY="$(LOCAL_AUDIT_PSEUDONYM_KEY)" \
	PEERGO_AUDIT_PSEUDONYM_KEY_EPOCH="$(LOCAL_AUDIT_PSEUDONYM_KEY_EPOCH)" \
	PEERGO_COOKIE_SECURE=false \
	PEERGO_WEB_ORIGINS="$(WEB_ORIGINS)" \
	PEERGO_PUBLIC_ORIGIN="$(LOCAL_PUBLIC_ORIGIN)" \
	PEERGO_TURNSTILE_SECRET_KEY="$(LOCAL_TURNSTILE_SECRET_KEY)" \
	go -C tools/devtools tool air -c ../../.air/core.toml

dev-worker:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_AUDIT_SINK_URL="$(AUDIT_SINK_URL)" \
	PEERGO_AUDIT_SERVICE_TOKEN="$(LOCAL_AUDIT_SERVICE_TOKEN)" \
	go run ./services/core/cmd/worker

# Image processing is intentionally isolated from the general Core worker: it
# needs native libvips and object-storage credentials, while audit/outbox jobs
# do not. Both queues still appear in the same staff monitoring surface.
dev-image-derivative-worker:
	mkdir -p "$(LOCAL_IMAGE_DERIVATIVE_TEMP_ROOT)"
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	PEERGO_IMAGE_DERIVATIVE_TEMP_DIR="$(LOCAL_IMAGE_DERIVATIVE_TEMP_ROOT)" \
	PEERGO_IMAGE_DERIVATIVE_VIPS_BINARY="vips" \
	go run ./services/core/cmd/image-derivative-worker

dev-image-derivative-worker-watch:
	mkdir -p "$(LOCAL_IMAGE_DERIVATIVE_TEMP_ROOT)"
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	PEERGO_IMAGE_DERIVATIVE_TEMP_DIR="$(LOCAL_IMAGE_DERIVATIVE_TEMP_ROOT)" \
	PEERGO_IMAGE_DERIVATIVE_VIPS_BINARY="vips" \
	go -C tools/devtools tool air -c ../../.air/image-derivative-worker.toml

# Promotion/H&R/workgroup delivery and Core-owned ratio, newcomer and H&R
# evaluations share one supervised process. Each still keeps its own repository
# and failure state, so one control does not silently mutate another domain.
dev-promotion-worker:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_SETTLEMENT_CONTROL_URL="$(LOCAL_SETTLEMENT_CONTROL_URL)" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	go run ./services/core/cmd/promotion-worker

dev-promotion-worker-watch:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_SETTLEMENT_CONTROL_URL="$(LOCAL_SETTLEMENT_CONTROL_URL)" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	go -C tools/devtools tool air -c ../../.air/promotion-worker.toml

# Preferred names. The legacy promotion-worker targets remain as aliases for
# existing local scripts. The process delivers independent policy outboxes and
# runs the bounded Core-owned assessment/enforcement loops.
dev-settlement-control-worker: dev-promotion-worker

dev-settlement-control-worker-watch: dev-promotion-worker-watch

# Reward settlement only receives the Core database credential.  It has no
# Tracker Ledger, NATS, Vault, object-storage or HTTP control-plane access.
dev-seeding-reward-worker:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/seeding-reward-worker

dev-seeding-reward-worker-watch:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go -C tools/devtools tool air -c ../../.air/seeding-reward-worker.toml

# Raw-upload GiB crossings, first torrent publication and complete account days
# share one progression-only worker. It receives only the Core database URL;
# Tracker evidence has already been privacy-minimized by the traffic projector.
dev-contribution-experience-worker:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/contribution-experience-worker

dev-contribution-experience-worker-watch:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go -C tools/devtools tool air -c ../../.air/contribution-experience-worker.toml

# Level activation is deliberately separate from experience calculation. At a
# scheduled boundary it atomically reprojects every account and records one
# immutable activation evidence row per affected user.
dev-progression-level-worker:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/progression-level-worker

dev-progression-level-worker-watch:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go -C tools/devtools tool air -c ../../.air/progression-level-worker.toml

dev-projector:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/projector

# This target uses the local operator identity to create a missing Core durable
# consumer or reject drift. The Core projector runtime cannot manage it.
dev-core-traffic-consumer:
	PEERGO_ENV=development \
	PEERGO_CORE_TRAFFIC_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_TRAFFIC_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_CORE_TRAFFIC_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_TRAFFIC_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_TRAFFIC_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM="$(LOCAL_SETTLEMENT_TRAFFIC_STREAM)" \
	PEERGO_SETTLEMENT_TRAFFIC_SUBJECT="$(LOCAL_SETTLEMENT_TRAFFIC_SUBJECT)" \
	PEERGO_CORE_TRAFFIC_DURABLE="$(LOCAL_CORE_TRAFFIC_DURABLE)" \
	PEERGO_CORE_TRAFFIC_FETCH_WAIT="2s" \
	PEERGO_CORE_TRAFFIC_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_TRAFFIC_ACK_TIMEOUT="5s" \
	PEERGO_CORE_TRAFFIC_CONSUMER_PROVISION_TIMEOUT="10s" \
	PEERGO_CORE_TRAFFIC_CONSUMER_ACK_WAIT="30s" \
	PEERGO_CORE_TRAFFIC_CONSUMER_MAX_WAITING="16" \
	PEERGO_CORE_TRAFFIC_CONSUMER_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/core/cmd/traffic-consumer-init

dev-core-traffic-projector:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_CORE_TRAFFIC_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_TRAFFIC_NATS_CREDENTIALS_FILE="" \
	PEERGO_CORE_TRAFFIC_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_TRAFFIC_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_TRAFFIC_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM="$(LOCAL_SETTLEMENT_TRAFFIC_STREAM)" \
	PEERGO_SETTLEMENT_TRAFFIC_SUBJECT="$(LOCAL_SETTLEMENT_TRAFFIC_SUBJECT)" \
	PEERGO_CORE_TRAFFIC_DURABLE="$(LOCAL_CORE_TRAFFIC_DURABLE)" \
	PEERGO_CORE_TRAFFIC_FETCH_WAIT="2s" \
	PEERGO_CORE_TRAFFIC_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_TRAFFIC_ACK_TIMEOUT="5s" \
	PEERGO_CORE_TRAFFIC_RETRY_DELAY="1s" \
	PEERGO_CORE_TRAFFIC_STARTUP_TIMEOUT="10s" \
	PEERGO_CORE_TRAFFIC_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/core/cmd/traffic-projector

# Closed hourly reward evidence has its own ordered durable. Core assembles and
# verifies the complete projection before any calculation worker can see it.
dev-core-seeding-evidence-consumer:
	PEERGO_ENV=development \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_STREAM)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT)" \
	PEERGO_CORE_SEEDING_EVIDENCE_DURABLE="$(LOCAL_CORE_SEEDING_EVIDENCE_DURABLE)" \
	PEERGO_CORE_SEEDING_EVIDENCE_FETCH_WAIT="2s" \
	PEERGO_CORE_SEEDING_EVIDENCE_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_SEEDING_EVIDENCE_ACK_TIMEOUT="5s" \
	PEERGO_CORE_SEEDING_EVIDENCE_CONSUMER_PROVISION_TIMEOUT="10s" \
	PEERGO_CORE_SEEDING_EVIDENCE_CONSUMER_ACK_WAIT="30s" \
	PEERGO_CORE_SEEDING_EVIDENCE_CONSUMER_MAX_WAITING="16" \
	PEERGO_CORE_SEEDING_EVIDENCE_CONSUMER_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/core/cmd/seeding-evidence-consumer-init

dev-core-seeding-evidence-projector:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_CREDENTIALS_FILE="" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_SEEDING_EVIDENCE_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_STREAM)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT)" \
	PEERGO_CORE_SEEDING_EVIDENCE_DURABLE="$(LOCAL_CORE_SEEDING_EVIDENCE_DURABLE)" \
	PEERGO_CORE_SEEDING_EVIDENCE_FETCH_WAIT="2s" \
	PEERGO_CORE_SEEDING_EVIDENCE_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_SEEDING_EVIDENCE_ACK_TIMEOUT="5s" \
	PEERGO_CORE_SEEDING_EVIDENCE_RETRY_DELAY="1s" \
	PEERGO_CORE_SEEDING_EVIDENCE_STARTUP_TIMEOUT="10s" \
	PEERGO_CORE_SEEDING_EVIDENCE_SHUTDOWN_TIMEOUT="10s" \
	PEERGO_CORE_SEEDING_EVIDENCE_MAX_FUTURE_SKEW="2m" \
	go run ./services/core/cmd/seeding-evidence-projector

dev-core-hnr-consumer:
	PEERGO_ENV=development \
	PEERGO_CORE_HNR_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_HNR_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_CORE_HNR_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_HNR_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_HNR_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_HNR_STREAM="$(LOCAL_SETTLEMENT_HNR_STREAM)" \
	PEERGO_SETTLEMENT_HNR_SUBJECT="$(LOCAL_SETTLEMENT_HNR_SUBJECT)" \
	PEERGO_CORE_HNR_DURABLE="$(LOCAL_CORE_HNR_DURABLE)" \
	PEERGO_CORE_HNR_FETCH_WAIT="2s" \
	PEERGO_CORE_HNR_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_HNR_ACK_TIMEOUT="5s" \
	PEERGO_CORE_HNR_CONSUMER_PROVISION_TIMEOUT="10s" \
	PEERGO_CORE_HNR_CONSUMER_ACK_WAIT="30s" \
	PEERGO_CORE_HNR_CONSUMER_MAX_WAITING="16" \
	PEERGO_CORE_HNR_CONSUMER_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/core/cmd/hnr-consumer-init

dev-core-hnr-projector:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_CORE_HNR_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_HNR_NATS_CREDENTIALS_FILE="" \
	PEERGO_CORE_HNR_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_HNR_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_HNR_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_HNR_STREAM="$(LOCAL_SETTLEMENT_HNR_STREAM)" \
	PEERGO_SETTLEMENT_HNR_SUBJECT="$(LOCAL_SETTLEMENT_HNR_SUBJECT)" \
	PEERGO_CORE_HNR_DURABLE="$(LOCAL_CORE_HNR_DURABLE)" \
	PEERGO_CORE_HNR_FETCH_WAIT="2s" \
	PEERGO_CORE_HNR_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_HNR_ACK_TIMEOUT="5s" \
	PEERGO_CORE_HNR_RETRY_DELAY="1s" \
	PEERGO_CORE_HNR_STARTUP_TIMEOUT="10s" \
	PEERGO_CORE_HNR_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/core/cmd/hnr-projector

# Core consumes active counts and completion identities through separate
# ordered durables. Only this operator target may create or inspect them.
dev-core-swarm-consumers:
	PEERGO_ENV=development \
	PEERGO_CORE_SWARM_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_SWARM_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_CORE_SWARM_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_SWARM_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_SWARM_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_CORE_SWARM_SNAPSHOT_DURABLE="$(LOCAL_CORE_SWARM_SNAPSHOT_DURABLE)" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_CORE_SWARM_COMPLETION_DURABLE="$(LOCAL_CORE_SWARM_COMPLETION_DURABLE)" \
	PEERGO_CORE_SWARM_FETCH_WAIT="2s" \
	PEERGO_CORE_SWARM_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_SWARM_ACK_TIMEOUT="5s" \
	PEERGO_CORE_SWARM_CONSUMER_PROVISION_TIMEOUT="10s" \
	PEERGO_CORE_SWARM_CONSUMER_ACK_WAIT="30s" \
	PEERGO_CORE_SWARM_CONSUMER_MAX_WAITING="16" \
	PEERGO_CORE_SWARM_CONSUMER_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/core/cmd/swarm-consumer-init

dev-core-swarm-projector:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_CORE_SWARM_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_CORE_SWARM_NATS_CREDENTIALS_FILE="" \
	PEERGO_CORE_SWARM_NATS_ROOT_CA_FILE="" \
	PEERGO_CORE_SWARM_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_CORE_SWARM_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_CORE_SWARM_SNAPSHOT_DURABLE="$(LOCAL_CORE_SWARM_SNAPSHOT_DURABLE)" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_CORE_SWARM_COMPLETION_DURABLE="$(LOCAL_CORE_SWARM_COMPLETION_DURABLE)" \
	PEERGO_CORE_SWARM_FETCH_WAIT="2s" \
	PEERGO_CORE_SWARM_PROCESS_TIMEOUT="10s" \
	PEERGO_CORE_SWARM_ACK_TIMEOUT="5s" \
	PEERGO_CORE_SWARM_RETRY_DELAY="1s" \
	PEERGO_CORE_SWARM_STARTUP_TIMEOUT="10s" \
	PEERGO_CORE_SWARM_SHUTDOWN_TIMEOUT="10s" \
	PEERGO_CORE_SWARM_MAX_FUTURE_SKEW="2m" \
	go run ./services/core/cmd/swarm-projector

dev-snapshot-builder:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_TRACKER_SNAPSHOT_KEY_ID="$(LOCAL_TRACKER_SNAPSHOT_KEY_ID)" \
	PEERGO_TRACKER_SNAPSHOT_SIGNING_KEY_BASE64="$(LOCAL_TRACKER_SNAPSHOT_SIGNING_SEED_BASE64)" \
	PEERGO_TRACKER_SNAPSHOT_PATH="$(LOCAL_TRACKER_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_PATH="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH)" \
	go run ./services/core/cmd/snapshot-builder

# Preferred local runtime: refreshes all three signed views before the
# one-minute subject freshness window expires. The command itself remains
# usable without the interval for one-shot cutover and acceptance workflows.
dev-snapshot-publisher:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_TRACKER_SNAPSHOT_KEY_ID="$(LOCAL_TRACKER_SNAPSHOT_KEY_ID)" \
	PEERGO_TRACKER_SNAPSHOT_SIGNING_KEY_BASE64="$(LOCAL_TRACKER_SNAPSHOT_SIGNING_SEED_BASE64)" \
	PEERGO_TRACKER_SNAPSHOT_PATH="$(LOCAL_TRACKER_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_PATH="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SNAPSHOT_PUBLISH_INTERVAL="30s" \
	go run ./services/core/cmd/snapshot-builder

tracker-snapshot-inspect:
	PEERGO_ENV=development \
	PEERGO_TRACKER_SNAPSHOT_PATH="$(LOCAL_TRACKER_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_PATH="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SNAPSHOT_TRUSTED_KEYS="$(LOCAL_TRACKER_SNAPSHOT_KEY_ID)=$(LOCAL_TRACKER_SNAPSHOT_PUBLIC_KEY_BASE64)" \
	PEERGO_TRACKER_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_SNAPSHOT_MAX_FUTURE_SKEW="$(LOCAL_TRACKER_SNAPSHOT_MAX_FUTURE_SKEW)" \
	PEERGO_TRACKER_PASSKEY_LOOKUP_KEY="$(LOCAL_TRACKER_PASSKEY_LOOKUP_KEY)" \
	go run ./services/tracker/cmd/snapshot-inspect

dev-tracker-stream:
	PEERGO_ENV=development \
	PEERGO_TRACKER_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_TRACKER_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_TRACKER_NATS_ROOT_CA_FILE="" \
	PEERGO_TRACKER_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_TRACKER_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_TRACKER_ANNOUNCE_STREAM_PROVISION_TIMEOUT="10s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM_MAX_BYTES="1073741824" \
	PEERGO_TRACKER_ANNOUNCE_STREAM_MAX_AGE="168h" \
	PEERGO_TRACKER_ANNOUNCE_STREAM_DUPLICATE_WINDOW="10m" \
	PEERGO_TRACKER_ANNOUNCE_STREAM_REPLICAS="1" \
	go run ./services/tracker/cmd/jetstream-init

# Complete snapshots have replaceable retention semantics and therefore use a
# separate stream from the append-like announce evidence stream.
dev-tracker-swarm-stream:
	PEERGO_ENV=development \
	PEERGO_TRACKER_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_TRACKER_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_TRACKER_NATS_ROOT_CA_FILE="" \
	PEERGO_TRACKER_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_TRACKER_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_TRACKER_SWARM_STREAM_PROVISION_TIMEOUT="10s" \
	PEERGO_TRACKER_SWARM_STREAM_MAX_BYTES="1073741824" \
	PEERGO_TRACKER_SWARM_STREAM_MAX_AGE="24h" \
	PEERGO_TRACKER_SWARM_STREAM_DUPLICATE_WINDOW="10m" \
	PEERGO_TRACKER_SWARM_STREAM_REPLICAS="1" \
	go run ./services/tracker/cmd/swarm-stream-init

# Local Tracker startup always verifies both JetStream streams first. The
# provisioners are idempotent and reject configuration drift, so a fresh
# checkout cannot silently run while announce or swarm events are discarded.
dev-tracker: dev-tracker-stream dev-tracker-swarm-stream
	PEERGO_ENV=development \
	PEERGO_TRACKER_SNAPSHOT_PATH="$(LOCAL_TRACKER_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_PATH="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_PATH)" \
	PEERGO_TRACKER_SNAPSHOT_TRUSTED_KEYS="$(LOCAL_TRACKER_SNAPSHOT_KEY_ID)=$(LOCAL_TRACKER_SNAPSHOT_PUBLIC_KEY_BASE64)" \
	PEERGO_TRACKER_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_SUBJECT_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_SUBJECT_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_RUNTIME_POLICY_SNAPSHOT_MAX_AGE="$(LOCAL_TRACKER_RUNTIME_POLICY_SNAPSHOT_MAX_AGE)" \
	PEERGO_TRACKER_SNAPSHOT_MAX_FUTURE_SKEW="$(LOCAL_TRACKER_SNAPSHOT_MAX_FUTURE_SKEW)" \
	PEERGO_TRACKER_PASSKEY_LOOKUP_KEY="$(LOCAL_TRACKER_PASSKEY_LOOKUP_KEY)" \
	PEERGO_TRACKER_LISTEN_ADDRESS="$(LOCAL_TRACKER_LISTEN_ADDRESS)" \
	PEERGO_TRACKER_METRICS_LISTEN_ADDRESS="$(LOCAL_TRACKER_METRICS_LISTEN_ADDRESS)" \
	PEERGO_TRACKER_SERVICE_TOKEN="$(LOCAL_TRACKER_SERVICE_TOKEN)" \
	PEERGO_TRACKER_SNAPSHOT_RELOAD_INTERVAL="5s" \
	PEERGO_TRACKER_SHUTDOWN_TIMEOUT="10s" \
	PEERGO_TRACKER_ANNOUNCE_INTERVAL_SECONDS="1800" \
	PEERGO_TRACKER_MIN_ANNOUNCE_INTERVAL_SECONDS="900" \
	PEERGO_TRACKER_DEFAULT_NUMWANT="50" \
	PEERGO_TRACKER_MAX_NUMWANT="100" \
	PEERGO_TRACKER_SWARM_SHARDS="16" \
	PEERGO_TRACKER_MAX_SWARMS="100000" \
	PEERGO_TRACKER_MAX_PEERS="1000000" \
	PEERGO_TRACKER_MAX_PEERS_PER_SWARM="100000" \
	PEERGO_TRACKER_PEER_TTL="35m" \
	PEERGO_TRACKER_SWEEP_BUDGET="64" \
	PEERGO_TRACKER_WAL_PATH="$(LOCAL_TRACKER_WAL_PATH)" \
	PEERGO_TRACKER_WAL_MAX_BYTES="1073741824" \
	PEERGO_TRACKER_WAL_COMPACT_AT_BYTES="1048576" \
	PEERGO_TRACKER_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_TRACKER_NATS_CREDENTIALS_FILE="" \
	PEERGO_TRACKER_NATS_ROOT_CA_FILE="" \
	PEERGO_TRACKER_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_TRACKER_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_TRACKER_ANNOUNCE_PUBLISH_TIMEOUT="3s" \
	PEERGO_TRACKER_ANNOUNCE_PUBLISH_RETRY_MIN="100ms" \
	PEERGO_TRACKER_ANNOUNCE_PUBLISH_RETRY_MAX="10s" \
	PEERGO_TRACKER_SWARM_SWEEP_INTERVAL="30s" \
	PEERGO_TRACKER_SWARM_SWEEP_SWARM_BUDGET="1000" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SOURCE_ID="$(LOCAL_TRACKER_SWARM_SOURCE_ID)" \
	PEERGO_TRACKER_SWARM_ROUTING_EPOCH="$(LOCAL_TRACKER_SWARM_ROUTING_EPOCH)" \
	PEERGO_TRACKER_SWARM_SEQUENCE_PATH="$(LOCAL_TRACKER_SWARM_SEQUENCE_PATH)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_INTERVAL="30s" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_MAX_CHUNK_ENTRIES="1000" \
	go run ./services/tracker/cmd/tracker

# This target uses the local operator identity to create a missing durable
# consumer or reject drift. The Settlement runtime never performs management.
dev-settlement-consumer:
	PEERGO_ENV=development \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_SETTLEMENT_ANNOUNCE_DURABLE="$(LOCAL_SETTLEMENT_ANNOUNCE_DURABLE)" \
	PEERGO_SETTLEMENT_FETCH_WAIT="2s" \
	PEERGO_SETTLEMENT_PROCESS_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_ACK_TIMEOUT="5s" \
	PEERGO_SETTLEMENT_CONSUMER_PROVISION_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_CONSUMER_ACK_WAIT="30s" \
	PEERGO_SETTLEMENT_CONSUMER_MAX_WAITING="16" \
	PEERGO_SETTLEMENT_CONSUMER_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/settlement/cmd/consumer-init

dev-settlement:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_ANNOUNCE_SUBJECT="$(LOCAL_TRACKER_ANNOUNCE_SUBJECT)" \
	PEERGO_SETTLEMENT_ANNOUNCE_DURABLE="$(LOCAL_SETTLEMENT_ANNOUNCE_DURABLE)" \
	PEERGO_SETTLEMENT_FETCH_WAIT="2s" \
	PEERGO_SETTLEMENT_PROCESS_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_ACK_TIMEOUT="5s" \
	PEERGO_SETTLEMENT_RETRY_DELAY="1s" \
	PEERGO_SETTLEMENT_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/settlement/cmd/settlement

# Settlement retains a historical full-snapshot copy for reward evidence. The
# operator target owns durable creation; the projector has read/ACK only.
dev-settlement-seeding-snapshot-consumer:
	PEERGO_ENV=development \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_DURABLE="$(LOCAL_SETTLEMENT_SEEDING_SNAPSHOT_DURABLE)" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_FETCH_WAIT="2s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_PROCESS_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_ACK_TIMEOUT="5s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_PROVISION_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_ACK_WAIT="30s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_WAITING="16" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_REQUEST_EXPIRES="5s" \
	go run ./services/settlement/cmd/seeding-snapshot-consumer-init

dev-settlement-seeding-snapshot-projector:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_DURABLE="$(LOCAL_SETTLEMENT_SEEDING_SNAPSHOT_DURABLE)" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_FETCH_WAIT="2s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_PROCESS_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_ACK_TIMEOUT="5s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_RETRY_DELAY="1s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_SHUTDOWN_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_FUTURE_SKEW="2m" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_CLOSURE_DELAY="15m" \
	go run ./services/settlement/cmd/seeding-snapshot-projector

# The worker only closes immutable source evidence. It does not know the magic
# point formula and cannot write Core economy accounts.
dev-settlement-seeding-evidence-worker:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_TRACKER_ANNOUNCE_STREAM="$(LOCAL_TRACKER_ANNOUNCE_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_STREAM="$(LOCAL_TRACKER_SWARM_SNAPSHOT_STREAM)" \
	PEERGO_TRACKER_SWARM_SNAPSHOT_SUBJECT="$(LOCAL_TRACKER_SWARM_SNAPSHOT_SUBJECT)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_START_AT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_START_AT)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_CLOSURE_DELAY="5m" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_CLOSURE_DELAY="15m" \
	PEERGO_SETTLEMENT_SEEDING_SNAPSHOT_MAX_FUTURE_SKEW="2m" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_IDLE_INTERVAL="5s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/settlement/cmd/seeding-evidence-worker

# Final policy settlement is deliberately separate from raw announce ingest:
# it only consumes Tracker Ledger work and cannot connect to NATS.
dev-settlement-policy:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_POLICY_LEASE_DURATION="30s" \
	PEERGO_SETTLEMENT_POLICY_IDLE_INTERVAL="500ms" \
	PEERGO_SETTLEMENT_POLICY_RETRY_BASE="1s" \
	PEERGO_SETTLEMENT_POLICY_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_POLICY_CONCURRENCY="4" \
	go run ./services/settlement/cmd/policy-worker

# Write-only loopback control API for immutable promotion commands from Core.
dev-settlement-promotion-control:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_CONTROL_ADDR="127.0.0.1:8085" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	go run ./services/settlement/cmd/promotion-control-api

dev-settlement-promotion-control-watch:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_CONTROL_ADDR="127.0.0.1:8085" \
	PEERGO_SETTLEMENT_CONTROL_SERVICE_TOKEN="$(LOCAL_SETTLEMENT_CONTROL_SERVICE_TOKEN)" \
	go -C tools/devtools tool air -c ../../.air/settlement-promotion-control.toml

# ARGS must include a complete compiled snapshot file and an immutable UUID;
# this command appends evidence and never edits a historical policy revision.
dev-settlement-policy-timeline:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	go run ./services/settlement/cmd/policy-timeline-append $(ARGS)

# The final traffic stream is owned by Settlement. Existing stream drift is an
# error; neither dispatcher nor Core projector can mutate it at runtime.
dev-settlement-traffic-stream:
	PEERGO_ENV=development \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_TRAFFIC_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM="$(LOCAL_SETTLEMENT_TRAFFIC_STREAM)" \
	PEERGO_SETTLEMENT_TRAFFIC_SUBJECT="$(LOCAL_SETTLEMENT_TRAFFIC_SUBJECT)" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM_PROVISION_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM_MAX_BYTES="1073741824" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM_MAX_AGE="168h" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM_DUPLICATE_WINDOW="10m" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM_REPLICAS="1" \
	go run ./services/settlement/cmd/traffic-stream-init

dev-settlement-traffic-dispatcher:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_PUBLISH_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_TRAFFIC_STREAM="$(LOCAL_SETTLEMENT_TRAFFIC_STREAM)" \
	PEERGO_SETTLEMENT_TRAFFIC_SUBJECT="$(LOCAL_SETTLEMENT_TRAFFIC_SUBJECT)" \
	PEERGO_SETTLEMENT_TRAFFIC_OUTBOX_LEASE_DURATION="30s" \
	PEERGO_SETTLEMENT_TRAFFIC_OUTBOX_IDLE_INTERVAL="500ms" \
	PEERGO_SETTLEMENT_TRAFFIC_OUTBOX_RETRY_BASE="1s" \
	PEERGO_SETTLEMENT_TRAFFIC_PUBLISH_TIMEOUT="3s" \
	PEERGO_SETTLEMENT_TRAFFIC_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_TRAFFIC_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/settlement/cmd/traffic-dispatcher

# The evidence stream is independent from final traffic and H&R results. It
# carries bounded chunks whose complete digest Core verifies before use.
dev-settlement-seeding-evidence-stream:
	PEERGO_ENV=development \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_SEEDING_EVIDENCE_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_STREAM)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM_PROVISION_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM_MAX_BYTES="1073741824" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM_MAX_AGE="720h" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM_DUPLICATE_WINDOW="10m" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM_REPLICAS="1" \
	go run ./services/settlement/cmd/seeding-evidence-stream-init

dev-settlement-seeding-evidence-dispatcher:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_SEEDING_EVIDENCE_PUBLISH_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STREAM="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_STREAM)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT="$(LOCAL_SETTLEMENT_SEEDING_EVIDENCE_SUBJECT)" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_OUTBOX_LEASE_DURATION="30s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_OUTBOX_IDLE_INTERVAL="500ms" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_OUTBOX_RETRY_BASE="1s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_PUBLISH_TIMEOUT="3s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_SEEDING_EVIDENCE_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/settlement/cmd/seeding-evidence-dispatcher

# H&R settings are an independent immutable timeline. ARGS must provide a
# canonical H&R policy file, entry UUID and effective time.
dev-settlement-hnr-policy-timeline:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	go run ./services/settlement/cmd/hnr-policy-timeline-append $(ARGS)

# H&R never runs in announce ingest. This worker reads post-cutover raw
# evidence and commits assessments, obligations and outbox rows atomically.
dev-settlement-hnr-worker:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_HNR_LEASE_DURATION="30s" \
	PEERGO_SETTLEMENT_HNR_IDLE_INTERVAL="500ms" \
	PEERGO_SETTLEMENT_HNR_RETRY_BASE="1s" \
	PEERGO_SETTLEMENT_HNR_STARTUP_TIMEOUT="10s" \
	go run ./services/settlement/cmd/hnr-worker

dev-settlement-hnr-stream:
	PEERGO_ENV=development \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_HNR_PROVISION_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_HNR_STREAM="$(LOCAL_SETTLEMENT_HNR_STREAM)" \
	PEERGO_SETTLEMENT_HNR_SUBJECT="$(LOCAL_SETTLEMENT_HNR_SUBJECT)" \
	PEERGO_SETTLEMENT_HNR_STREAM_PROVISION_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_HNR_STREAM_MAX_BYTES="1073741824" \
	PEERGO_SETTLEMENT_HNR_STREAM_MAX_AGE="720h" \
	PEERGO_SETTLEMENT_HNR_STREAM_DUPLICATE_WINDOW="10m" \
	PEERGO_SETTLEMENT_HNR_STREAM_REPLICAS="1" \
	go run ./services/settlement/cmd/hnr-stream-init

dev-settlement-hnr-dispatcher:
	PEERGO_ENV=development \
	PEERGO_TRACKER_DATABASE_URL="$(TRACKER_DATABASE_URL)" \
	PEERGO_SETTLEMENT_NATS_URLS="$(LOCAL_TRACKER_NATS_URLS)" \
	PEERGO_SETTLEMENT_NATS_HNR_PUBLISH_CREDENTIALS_FILE="" \
	PEERGO_SETTLEMENT_NATS_ROOT_CA_FILE="" \
	PEERGO_SETTLEMENT_NATS_CONNECT_TIMEOUT="2s" \
	PEERGO_SETTLEMENT_NATS_RECONNECT_WAIT="1s" \
	PEERGO_SETTLEMENT_HNR_STREAM="$(LOCAL_SETTLEMENT_HNR_STREAM)" \
	PEERGO_SETTLEMENT_HNR_SUBJECT="$(LOCAL_SETTLEMENT_HNR_SUBJECT)" \
	PEERGO_SETTLEMENT_HNR_OUTBOX_LEASE_DURATION="30s" \
	PEERGO_SETTLEMENT_HNR_OUTBOX_IDLE_INTERVAL="500ms" \
	PEERGO_SETTLEMENT_HNR_OUTBOX_RETRY_BASE="1s" \
	PEERGO_SETTLEMENT_HNR_PUBLISH_TIMEOUT="3s" \
	PEERGO_SETTLEMENT_HNR_STARTUP_TIMEOUT="10s" \
	PEERGO_SETTLEMENT_HNR_SHUTDOWN_TIMEOUT="10s" \
	go run ./services/settlement/cmd/hnr-dispatcher

# Runs fixed, client-shaped HTTP announces through Tracker's real PGW1 WAL and
# publisher, then through Settlement and Core. The harness uses only synthetic
# loopback admissions and never inserts Core traffic rows or totals directly.
dev-traffic-demo:
	sh ./tools/traffic-corpus/run-local.sh

dev-audit:
	mkdir -p "$(dir $(AUDIT_JOURNAL_PATH))"
	PEERGO_ENV=development \
	PEERGO_AUDIT_JOURNAL_PATH="$(AUDIT_JOURNAL_PATH)" \
	PEERGO_AUDIT_SERVICE_TOKEN="$(LOCAL_AUDIT_SERVICE_TOKEN)" \
	go run ./services/audit-sink/cmd/audit-sink

# Source/destination backend variables are intentionally supplied by the
# operator. See .env.example; credentials must not be committed to this file.
dev-object-storage:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/object-storage $(ARGS)

# Compatibility alias for old local notes. New migrations include .torrent,
# screenshots, avatars and verified WebP derivatives in one manifest.
dev-torrent-storage: dev-object-storage

dev-torrent-upload-reconcile:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	go run ./services/core/cmd/torrent-upload-reconcile $(ARGS)

# Site administrators use their existing account login. These commands are
# idempotent and never infer authority from a legacy user level or user ID.
admin:
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/admin --username "$(USERNAME)"

admin-revoke:
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	go run ./services/core/cmd/admin --username "$(USERNAME)" --revoke

# USERNAME and OPERATOR_REFERENCE are intentionally required at invocation.
# The command prints the raw ticket once; PostgreSQL and audit store hashes.
staff-bootstrap:
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_AUDIT_PSEUDONYM_KEY="$(LOCAL_AUDIT_PSEUDONYM_KEY)" \
	PEERGO_AUDIT_PSEUDONYM_KEY_EPOCH="$(LOCAL_AUDIT_PSEUDONYM_KEY_EPOCH)" \
	go run ./services/core/cmd/staff-bootstrap \
		--username "$(USERNAME)" \
		--operator-reference "$(OPERATOR_REFERENCE)"

compose-up:
	docker compose -f deploy/compose/compose.yaml up -d --wait
	$(MAKE) dev-tracker-stream
	$(MAKE) dev-tracker-swarm-stream
	$(MAKE) dev-settlement-consumer
	$(MAKE) dev-settlement-seeding-snapshot-consumer
	$(MAKE) dev-settlement-traffic-stream
	$(MAKE) dev-settlement-seeding-evidence-stream
	$(MAKE) dev-settlement-hnr-stream
	$(MAKE) dev-core-traffic-consumer
	$(MAKE) dev-core-seeding-evidence-consumer
	$(MAKE) dev-core-hnr-consumer
	$(MAKE) dev-core-swarm-consumers

compose-down:
	docker compose -f deploy/compose/compose.yaml down

# Production orchestration intentionally uses an untracked environment file.
# The wrapper keeps cluster as the default and selects the private single-host
# overlay only when PEERGO_DEPLOYMENT_MODE=single-server is explicit.
production-config:
	./scripts/production-compose.sh config --quiet

production-ready: production-config
	./scripts/validate-production-env.sh

production-build: production-config
	# Every Go process uses the same runtime image. Building one representative
	# service avoids Docker Compose 5 exporting that tag concurrently per service.
	./scripts/production-compose.sh build core-api web

production-up: production-ready production-build
	./scripts/production-compose.sh up -d --wait

production-down: production-config
	./scripts/production-compose.sh down

production-status: production-config
	./scripts/production-compose.sh ps

# Run only after the administrator has reviewed registration, newcomer,
# promotion and H&R policies, and sent a real test email from the backend.
# It is read-only and also requires the production Relay status to be healthy.
production-activation-check: production-config
	./scripts/production-compose.sh --profile activation run --rm --no-deps activation-check

# Direct-cutover installations can configure the three activation policies
# through the loopback Web API before the public reverse proxy is switched.
# The operator password is read from the terminal and is never an argument.
production-policy-bootstrap: production-config
	test -n "$(USERNAME)"
	test "$(CONFIRM_PEERGO_PRODUCTION_POLICIES)" = "APPLY_PEERGO_PRODUCTION_POLICIES"
	command -v python3 >/dev/null
	python3 ./scripts/bootstrap_production_policies.py \
		--env-file "$${PEERGO_PRODUCTION_ENV_FILE:-$(CURDIR)/.env.production}" \
		--username "$(USERNAME)" \
		--confirm "$(CONFIRM_PEERGO_PRODUCTION_POLICIES)"

# The first administrator is always an explicit existing account. Migration
# order, numeric ID or legacy level never grants site administration.
production-admin: production-config
	test -n "$(USERNAME)"
	./scripts/production-compose.sh \
		run --rm --no-deps --entrypoint core-admin core-api --username "$(USERNAME)"

production-admin-revoke: production-config
	test -n "$(USERNAME)"
	./scripts/production-compose.sh \
		run --rm --no-deps --entrypoint core-admin core-api --username "$(USERNAME)" --revoke

db-migrate:
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/core/migrations postgres "$(CORE_DATABASE_URL)" up
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/vault/migrations postgres "$(VAULT_DATABASE_URL)" up
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/tracker/migrations postgres "$(TRACKER_DATABASE_URL)" up

db-status:
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/core/migrations postgres "$(CORE_DATABASE_URL)" status
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/vault/migrations postgres "$(VAULT_DATABASE_URL)" status
	GOWORK=off go -C tools/migrator tool goose -dir ../../db/tracker/migrations postgres "$(TRACKER_DATABASE_URL)" status

db-seed:
	docker compose -f deploy/compose/compose.yaml exec -T core-postgres psql -v ON_ERROR_STOP=1 -U peergo_core -d peergo_core -f /dev/stdin < db/core/seeds/development.sql
	PEERGO_ENV=development \
	PEERGO_CORE_DATABASE_URL="$(CORE_DATABASE_URL)" \
	PEERGO_AUDIT_PSEUDONYM_KEY="$(LOCAL_AUDIT_PSEUDONYM_KEY)" \
	PEERGO_AUDIT_PSEUDONYM_KEY_EPOCH="$(LOCAL_AUDIT_PSEUDONYM_KEY_EPOCH)" \
	PEERGO_TORRENT_STORAGE_BACKEND_ID="local-primary" \
	PEERGO_TORRENT_STORAGE_DRIVER="filesystem" \
	PEERGO_TORRENT_STORAGE_FILESYSTEM_ROOT="$(LOCAL_TORRENT_OBJECT_ROOT)" \
	go run ./services/core/cmd/devseed
	PEERGO_ENV=development \
	PEERGO_VAULT_DATABASE_URL="$(VAULT_DATABASE_URL)" \
	PEERGO_VAULT_IDENTIFIER_KEY="$(LOCAL_VAULT_IDENTIFIER_KEY)" \
	PEERGO_DEV_PASSWORD="$(DEMO_PASSWORD)" \
	go run ./services/privacy-vault/cmd/devseed
