-- +goose Up

CREATE SCHEMA IF NOT EXISTS social;

-- A thread is the reusable discussion aggregate. The first vertical slice only
-- enables torrent targets; future target kinds must add their own typed binding
-- table instead of storing an unchecked target_type/target_id pair.
CREATE TABLE social.comment_threads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    target_kind text NOT NULL CHECK (target_kind IN ('torrent')),
    state text NOT NULL DEFAULT 'open' CHECK (state IN ('open', 'locked')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (id, target_kind),
    CHECK (updated_at >= created_at)
);

-- The strong binding keeps comment ownership in social while retaining a real
-- foreign key to the torrent aggregate. Disabled/deleted torrents keep their
-- thread as a tombstone; public queries independently require published state.
CREATE TABLE social.torrent_comment_threads (
    thread_id bigint PRIMARY KEY,
    target_kind text NOT NULL DEFAULT 'torrent' CHECK (target_kind = 'torrent'),
    torrent_id bigint NOT NULL UNIQUE
        REFERENCES torrents.torrents (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL,
    FOREIGN KEY (thread_id, target_kind)
        REFERENCES social.comment_threads (id, target_kind) ON DELETE RESTRICT
);

CREATE TABLE social.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    thread_id bigint NOT NULL
        REFERENCES social.comment_threads (id) ON DELETE RESTRICT,
    parent_comment_id bigint,
    author_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    create_request_id uuid NOT NULL,
    create_body_sha256 bytea NOT NULL
        CHECK (octet_length(create_body_sha256) = 32),
    body text NOT NULL,
    body_format text NOT NULL DEFAULT 'plain_text'
        CHECK (body_format IN ('plain_text', 'legacy_bbcode')),
    state text NOT NULL DEFAULT 'visible'
        CHECK (state IN ('visible', 'author_deleted', 'moderator_hidden')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    edited_at timestamptz,
    deleted_at timestamptz,
    UNIQUE (id, thread_id),
    UNIQUE (author_id, create_request_id),
    FOREIGN KEY (parent_comment_id, thread_id)
        REFERENCES social.comments (id, thread_id) ON DELETE RESTRICT,
    CHECK (parent_comment_id IS NULL OR parent_comment_id <> id),
    CHECK (char_length(body) <= 2000),
    CHECK (
        (state = 'visible' AND char_length(btrim(body)) BETWEEN 1 AND 2000 AND deleted_at IS NULL)
        OR
        (state <> 'visible' AND body = '' AND deleted_at IS NOT NULL)
    ),
    CHECK (updated_at >= created_at),
    CHECK (edited_at IS NULL OR (edited_at >= created_at AND edited_at <= updated_at)),
    CHECK (deleted_at IS NULL OR (deleted_at >= created_at AND deleted_at <= updated_at))
);

CREATE INDEX comments_thread_chronological_idx
    ON social.comments (thread_id, created_at, id);

CREATE INDEX comments_author_recent_idx
    ON social.comments (author_id, created_at DESC, id DESC);

-- Revisions are internal evidence for bounded edit/delete governance. They are
-- not exposed by the public comment DTO and cannot be rewritten after append.
CREATE TABLE social.comment_revisions (
    comment_id bigint NOT NULL
        REFERENCES social.comments (id) ON DELETE RESTRICT,
    version bigint NOT NULL CHECK (version > 0),
    body text NOT NULL CHECK (char_length(btrim(body)) BETWEEN 1 AND 2000),
    body_format text NOT NULL
        CHECK (body_format IN ('plain_text', 'legacy_bbcode')),
    reason text NOT NULL
        CHECK (reason IN ('author_edit', 'author_delete', 'moderator_hide')),
    editor_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (comment_id, version)
);

-- +goose StatementBegin
CREATE FUNCTION social.validate_comment_parent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_state text;
BEGIN
    IF NEW.parent_comment_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT parent.state
    INTO parent_state
    FROM social.comments AS parent
    WHERE parent.id = NEW.parent_comment_id
      AND parent.thread_id = NEW.thread_id;

    IF NOT FOUND OR parent_state <> 'visible' THEN
        RAISE EXCEPTION 'comment parent must be visible in the same thread'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER comment_parent_valid
BEFORE INSERT ON social.comments
FOR EACH ROW EXECUTE FUNCTION social.validate_comment_parent();

-- +goose StatementBegin
CREATE FUNCTION social.protect_comment_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'comments must be tombstoned, not deleted';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
        OR OLD.public_id IS DISTINCT FROM NEW.public_id
        OR OLD.thread_id IS DISTINCT FROM NEW.thread_id
        OR OLD.parent_comment_id IS DISTINCT FROM NEW.parent_comment_id
        OR OLD.author_id IS DISTINCT FROM NEW.author_id
        OR OLD.create_request_id IS DISTINCT FROM NEW.create_request_id
        OR OLD.create_body_sha256 IS DISTINCT FROM NEW.create_body_sha256
        OR OLD.body_format IS DISTINCT FROM NEW.body_format
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'comment identity is immutable';
    END IF;
    IF NEW.version <> OLD.version + 1 OR NEW.updated_at < OLD.updated_at THEN
        RAISE EXCEPTION 'comment version and update time must advance exactly once';
    END IF;
    IF OLD.state <> 'visible' THEN
        RAISE EXCEPTION 'comment tombstones are terminal';
    END IF;

    IF NEW.state = 'visible' THEN
        IF NEW.body IS NOT DISTINCT FROM OLD.body
            OR NEW.edited_at IS DISTINCT FROM NEW.updated_at
            OR NEW.deleted_at IS NOT NULL THEN
            RAISE EXCEPTION 'visible comment update must be a body edit';
        END IF;
    ELSIF NEW.state IN ('author_deleted', 'moderator_hidden') THEN
        IF NEW.body <> ''
            OR NEW.deleted_at IS DISTINCT FROM NEW.updated_at
            OR NEW.edited_at IS DISTINCT FROM OLD.edited_at THEN
            RAISE EXCEPTION 'comment deletion must create a terminal tombstone';
        END IF;
    ELSE
        RAISE EXCEPTION 'invalid comment state transition';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER comment_history_protected
BEFORE UPDATE OR DELETE ON social.comments
FOR EACH ROW EXECUTE FUNCTION social.protect_comment_history();

-- +goose StatementBegin
CREATE FUNCTION social.reject_comment_revision_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'comment revisions are immutable';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER comment_revisions_immutable
BEFORE UPDATE OR DELETE ON social.comment_revisions
FOR EACH ROW EXECUTE FUNCTION social.reject_comment_revision_mutation();

INSERT INTO authz.permissions (
    action,
    description,
    risk_level,
    relationship,
    credential_audience,
    grantable,
    discoverable
) VALUES
    (
        'comment.delete.self',
        '删除自己的评论',
        'low',
        'self',
        'web-session',
        true,
        true
    ),
    (
        'comment.update.self',
        '编辑自己的评论',
        'low',
        'self',
        'web-session',
        true,
        true
    ),
    (
        'torrent.comment.create.self',
        '在已发布种子下发表评论',
        'low',
        'self',
        'web-session',
        true,
        true
    );

INSERT INTO authz.role_permissions (role_id, action) VALUES
    ('member', 'comment.delete.self'),
    ('member', 'comment.update.self'),
    ('member', 'torrent.comment.create.self');

-- +goose Down

DELETE FROM authz.role_permissions
WHERE role_id = 'member'
  AND action IN (
      'comment.delete.self',
      'comment.update.self',
      'torrent.comment.create.self'
  );

DELETE FROM authz.permissions
WHERE action IN (
    'comment.delete.self',
    'comment.update.self',
    'torrent.comment.create.self'
);

DROP SCHEMA IF EXISTS social CASCADE;
