-- +goose Up

-- Medal definitions and ownership are ordinary Core domain data.  The
-- migration receipts below remain separate and immutable so the finite Rousi
-- cutover can prove exactly which source rows created these records without
-- making runtime medal state append-only.
CREATE TABLE economy.medal_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    description text,
    image_large_path text,
    image_small_path text,
    acquisition_method text NOT NULL CHECK (
        acquisition_method IN ('purchase', 'grant', 'sponsor', 'workgroup', 'developer')
    ),
    price bigint NOT NULL CHECK (price >= 0),
    duration_days bigint NOT NULL CHECK (duration_days >= 0),
    display_on_page boolean NOT NULL,
    priority bigint NOT NULL,
    upload_bonus_bps bigint NOT NULL CHECK (upload_bonus_bps BETWEEN 0 AND 100000),
    download_discount_bps bigint NOT NULL CHECK (download_discount_bps BETWEEN 0 AND 100000),
    magic_bonus_bps bigint NOT NULL CHECK (magic_bonus_bps BETWEEN 0 AND 100000),
    invite_bonus bigint NOT NULL CHECK (invite_bonus >= 0),
    is_workgroup boolean NOT NULL,
    conditions jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(conditions) = 'array'),
    privileges jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(privileges) = 'array'),
    pool_eligible boolean NOT NULL,
    periodic_reward_magic bigint NOT NULL CHECK (periodic_reward_magic >= 0),
    reward_cycle text CHECK (
        reward_cycle IS NULL OR reward_cycle ~ '^[a-z][a-z0-9_-]{0,19}$'
    ),
    sale_begin_at timestamptz,
    sale_end_at timestamptz,
    inventory bigint CHECK (inventory IS NULL OR inventory >= 0),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK (sale_end_at IS NULL OR sale_begin_at IS NULL OR sale_begin_at < sale_end_at)
);

CREATE INDEX medal_definitions_display_idx
    ON economy.medal_definitions (display_on_page, priority DESC, id);

CREATE TABLE economy.user_medals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES identity.users (id) ON DELETE RESTRICT,
    medal_id bigint NOT NULL REFERENCES economy.medal_definitions (id) ON DELETE RESTRICT,
    state text NOT NULL CHECK (state IN ('owned', 'wearing')),
    priority bigint NOT NULL,
    expires_at timestamptz,
    granted_by uuid REFERENCES identity.users (id) ON DELETE RESTRICT,
    note text CHECK (note IS NULL OR length(note) <= 255),
    acquired_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    last_reward_at timestamptz,
    UNIQUE (user_id, medal_id)
);

CREATE INDEX user_medals_active_idx
    ON economy.user_medals (user_id, expires_at, state);
CREATE INDEX user_medals_medal_idx
    ON economy.user_medals (medal_id, user_id);

-- The source settings are part of the opening evidence.  In particular, the
-- live Rousi magic-bonus cap is 100%, so reward settlement must not silently
-- substitute a PeerGo UI default.
CREATE TABLE migration.medal_system_openings (
    source_system text PRIMARY KEY CHECK (source_system = 'ptyes'),
    enabled boolean NOT NULL,
    maximum_wear_count bigint NOT NULL CHECK (maximum_wear_count >= 0),
    maximum_upload_bonus_bps bigint NOT NULL CHECK (maximum_upload_bonus_bps BETWEEN 0 AND 100000),
    maximum_download_discount_bps bigint NOT NULL CHECK (maximum_download_discount_bps BETWEEN 0 AND 100000),
    maximum_magic_bonus_bps bigint NOT NULL CHECK (maximum_magic_bonus_bps BETWEEN 0 AND 100000),
    maximum_invite_bonus bigint NOT NULL CHECK (maximum_invite_bonus >= 0),
    condition_check_day bigint NOT NULL CHECK (condition_check_day BETWEEN 1 AND 28),
    condition_warning_days bigint NOT NULL CHECK (condition_warning_days >= 0),
    source_fingerprint bytea NOT NULL CHECK (octet_length(source_fingerprint) = 32),
    first_run_id uuid NOT NULL REFERENCES migration.runs (id) ON DELETE RESTRICT,
    imported_at timestamptz NOT NULL
);

CREATE TABLE migration.medal_definition_openings (
    source_system text NOT NULL CHECK (source_system = 'ptyes'),
    legacy_medal_id bigint NOT NULL CHECK (legacy_medal_id > 0),
    medal_id bigint NOT NULL REFERENCES economy.medal_definitions (id) ON DELETE RESTRICT,
    source_get_type bigint NOT NULL CHECK (source_get_type BETWEEN 1 AND 5),
    source_price numeric NOT NULL,
    source_upload_bonus numeric NOT NULL,
    source_download_discount numeric NOT NULL,
    source_magic_bonus numeric NOT NULL,
    source_reward_magic numeric NOT NULL,
    source_reward_credits numeric NOT NULL,
    source_conditions text,
    source_privileges text,
    source_image_large text,
    source_image_small text,
    source_fingerprint bytea NOT NULL CHECK (octet_length(source_fingerprint) = 32),
    first_run_id uuid NOT NULL REFERENCES migration.runs (id) ON DELETE RESTRICT,
    imported_at timestamptz NOT NULL,
    PRIMARY KEY (source_system, legacy_medal_id),
    UNIQUE (medal_id),
    CHECK (legacy_medal_id = medal_id)
);

CREATE TABLE migration.user_medal_openings (
    source_system text NOT NULL CHECK (source_system = 'ptyes'),
    legacy_user_medal_id bigint NOT NULL CHECK (legacy_user_medal_id > 0),
    user_medal_id bigint NOT NULL REFERENCES economy.user_medals (id) ON DELETE RESTRICT,
    legacy_user_id bigint NOT NULL CHECK (legacy_user_id > 0),
    user_id uuid NOT NULL REFERENCES identity.users (id) ON DELETE RESTRICT,
    legacy_medal_id bigint NOT NULL CHECK (legacy_medal_id > 0),
    medal_id bigint NOT NULL REFERENCES economy.medal_definitions (id) ON DELETE RESTRICT,
    source_status bigint NOT NULL CHECK (source_status IN (1, 2)),
    source_priority bigint NOT NULL,
    source_expires_at timestamptz,
    legacy_granted_by bigint CHECK (legacy_granted_by IS NULL OR legacy_granted_by > 0),
    granted_by uuid REFERENCES identity.users (id) ON DELETE RESTRICT,
    source_fingerprint bytea NOT NULL CHECK (octet_length(source_fingerprint) = 32),
    first_run_id uuid NOT NULL REFERENCES migration.runs (id) ON DELETE RESTRICT,
    imported_at timestamptz NOT NULL,
    PRIMARY KEY (source_system, legacy_user_medal_id),
    UNIQUE (user_medal_id),
    UNIQUE (source_system, legacy_user_id, legacy_medal_id),
    FOREIGN KEY (source_system, legacy_user_id, user_id)
        REFERENCES migration.user_id_map (source_system, legacy_user_id, user_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (source_system, legacy_medal_id)
        REFERENCES migration.medal_definition_openings (source_system, legacy_medal_id)
        ON DELETE RESTRICT,
    CHECK (legacy_user_medal_id = user_medal_id),
    CHECK (legacy_medal_id = medal_id),
    CHECK ((legacy_granted_by IS NULL) = (granted_by IS NULL))
);

-- One receipt per migrated user freezes the source-site aggregation result at
-- cutover.  It also links the exact revision used by hourly seeding rewards.
CREATE TABLE migration.medal_benefit_openings (
    source_system text NOT NULL CHECK (source_system = 'ptyes'),
    legacy_user_id bigint NOT NULL CHECK (legacy_user_id > 0),
    user_id uuid NOT NULL REFERENCES identity.users (id) ON DELETE RESTRICT,
    active_contributing_medals bigint NOT NULL CHECK (active_contributing_medals >= 0),
    uncapped_magic_bonus_bps bigint NOT NULL CHECK (uncapped_magic_bonus_bps >= 0),
    magic_bonus_bps bigint NOT NULL CHECK (magic_bonus_bps BETWEEN 0 AND 100000),
    benefit_revision bigint NOT NULL CHECK (benefit_revision > 1),
    effective_from timestamptz NOT NULL,
    source_fingerprint bytea NOT NULL CHECK (octet_length(source_fingerprint) = 32),
    first_run_id uuid NOT NULL REFERENCES migration.runs (id) ON DELETE RESTRICT,
    imported_at timestamptz NOT NULL,
    PRIMARY KEY (source_system, legacy_user_id),
    UNIQUE (user_id),
    FOREIGN KEY (source_system, legacy_user_id, user_id)
        REFERENCES migration.user_id_map (source_system, legacy_user_id, user_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (user_id, benefit_revision)
        REFERENCES identity.user_reward_benefit_revisions (user_id, revision)
        ON DELETE RESTRICT,
    CHECK (effective_from = imported_at)
);

CREATE TRIGGER migration_medal_system_openings_immutable
BEFORE UPDATE OR DELETE ON migration.medal_system_openings
FOR EACH ROW EXECUTE FUNCTION migration.reject_append_only_mutation();

CREATE TRIGGER migration_medal_definition_openings_immutable
BEFORE UPDATE OR DELETE ON migration.medal_definition_openings
FOR EACH ROW EXECUTE FUNCTION migration.reject_append_only_mutation();

CREATE TRIGGER migration_user_medal_openings_immutable
BEFORE UPDATE OR DELETE ON migration.user_medal_openings
FOR EACH ROW EXECUTE FUNCTION migration.reject_append_only_mutation();

CREATE TRIGGER migration_medal_benefit_openings_immutable
BEFORE UPDATE OR DELETE ON migration.medal_benefit_openings
FOR EACH ROW EXECUTE FUNCTION migration.reject_append_only_mutation();

REVOKE ALL ON economy.medal_definitions FROM PUBLIC;
REVOKE ALL ON economy.user_medals FROM PUBLIC;
REVOKE ALL ON migration.medal_system_openings FROM PUBLIC;
REVOKE ALL ON migration.medal_definition_openings FROM PUBLIC;
REVOKE ALL ON migration.user_medal_openings FROM PUBLIC;
REVOKE ALL ON migration.medal_benefit_openings FROM PUBLIC;

-- +goose Down

DROP TRIGGER migration_medal_benefit_openings_immutable
    ON migration.medal_benefit_openings;
DROP TRIGGER migration_user_medal_openings_immutable
    ON migration.user_medal_openings;
DROP TRIGGER migration_medal_definition_openings_immutable
    ON migration.medal_definition_openings;
DROP TRIGGER migration_medal_system_openings_immutable
    ON migration.medal_system_openings;
DROP TABLE migration.medal_benefit_openings;
DROP TABLE migration.user_medal_openings;
DROP TABLE migration.medal_definition_openings;
DROP TABLE migration.medal_system_openings;
DROP TABLE economy.user_medals;
DROP TABLE economy.medal_definitions;
