-- +goose Up

-- One open case aggregates all reports against the same comment. A terminal
-- case remains immutable evidence; a later report against a still-visible
-- comment creates a new case instead of reopening or rewriting old evidence.
CREATE TABLE social.comment_moderation_cases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    comment_id bigint NOT NULL
        REFERENCES social.comments (id) ON DELETE RESTRICT,
    state text NOT NULL DEFAULT 'open'
        CHECK (state IN ('open', 'dismissed', 'comment_hidden')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    opened_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    resolved_at timestamptz,
    CHECK (updated_at >= opened_at),
    CHECK (resolved_at IS NULL OR (resolved_at >= opened_at AND resolved_at <= updated_at)),
    CHECK (
        (state = 'open' AND resolved_at IS NULL)
        OR
        (state <> 'open' AND resolved_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX comment_moderation_cases_one_open_per_comment_idx
    ON social.comment_moderation_cases (comment_id)
    WHERE state = 'open';

CREATE INDEX comment_moderation_cases_open_queue_idx
    ON social.comment_moderation_cases (opened_at, id)
    WHERE state = 'open';

-- Reports are immutable user statements. Reporter identity remains in Core for
-- conflict-of-interest enforcement but is intentionally absent from staff DTOs
-- and external audit payloads.
CREATE TABLE social.comment_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    case_id bigint NOT NULL
        REFERENCES social.comment_moderation_cases (id) ON DELETE RESTRICT,
    reporter_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    create_request_id uuid NOT NULL,
    create_input_sha256 bytea NOT NULL
        CHECK (octet_length(create_input_sha256) = 32),
    reason_code text NOT NULL
        CHECK (reason_code IN ('spam', 'harassment', 'personal_information', 'off_topic', 'other')),
    details text NOT NULL DEFAULT '' CHECK (char_length(details) <= 500),
    created_at timestamptz NOT NULL,
    UNIQUE (reporter_id, create_request_id),
    UNIQUE (case_id, reporter_id)
);

CREATE INDEX comment_reports_case_chronological_idx
    ON social.comment_reports (case_id, created_at, id);

-- A case has at most one immutable decision. Keeping the command UUID and
-- canonical human note here makes lost-response retries comparable without
-- putting editable text into the audit stream.
CREATE TABLE social.comment_moderation_decisions (
    id uuid PRIMARY KEY,
    case_id bigint NOT NULL UNIQUE
        REFERENCES social.comment_moderation_cases (id) ON DELETE RESTRICT,
    case_public_id uuid NOT NULL,
    comment_public_id uuid NOT NULL,
    torrent_public_id uuid NOT NULL,
    moderator_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    decision text NOT NULL CHECK (decision IN ('dismiss', 'hide_comment')),
    reason_code text NOT NULL
        CHECK (reason_code IN ('no_violation', 'spam', 'harassment', 'personal_information', 'off_topic', 'other')),
    note text NOT NULL CHECK (char_length(btrim(note)) BETWEEN 10 AND 1000),
    expected_case_version bigint NOT NULL CHECK (expected_case_version > 0),
    resulting_case_version bigint NOT NULL CHECK (resulting_case_version = expected_case_version + 1),
    expected_comment_version bigint NOT NULL CHECK (expected_comment_version > 0),
    resulting_comment_version bigint NOT NULL CHECK (resulting_comment_version >= expected_comment_version),
    resulting_case_state text NOT NULL
        CHECK (resulting_case_state IN ('dismissed', 'comment_hidden')),
    resulting_comment_state text NOT NULL
        CHECK (resulting_comment_state IN ('visible', 'author_deleted', 'moderator_hidden')),
    authorization_decision_id uuid NOT NULL,
    decided_at timestamptz NOT NULL,
    CHECK (
        (decision = 'dismiss' AND reason_code = 'no_violation' AND resulting_case_state = 'dismissed')
        OR
        (decision = 'hide_comment' AND reason_code <> 'no_violation'
            AND resulting_case_state = 'comment_hidden'
            AND resulting_comment_state = 'moderator_hidden'
            AND resulting_comment_version = expected_comment_version + 1)
    )
);

-- +goose StatementBegin
CREATE FUNCTION social.protect_comment_moderation_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'comment moderation cases cannot be deleted';
    END IF;
    IF OLD.id IS DISTINCT FROM NEW.id
        OR OLD.public_id IS DISTINCT FROM NEW.public_id
        OR OLD.comment_id IS DISTINCT FROM NEW.comment_id
        OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'comment moderation case identity is immutable';
    END IF;
    IF OLD.state <> 'open'
        OR NEW.state NOT IN ('dismissed', 'comment_hidden')
        OR NEW.version <> OLD.version + 1
        OR NEW.updated_at < OLD.updated_at
        OR NEW.resolved_at IS DISTINCT FROM NEW.updated_at THEN
        RAISE EXCEPTION 'comment moderation case transition is invalid';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER comment_moderation_case_protected
BEFORE UPDATE OR DELETE ON social.comment_moderation_cases
FOR EACH ROW EXECUTE FUNCTION social.protect_comment_moderation_case();

-- +goose StatementBegin
CREATE FUNCTION social.reject_comment_moderation_evidence_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'comment moderation evidence is immutable';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER comment_reports_immutable
BEFORE UPDATE OR DELETE ON social.comment_reports
FOR EACH ROW EXECUTE FUNCTION social.reject_comment_moderation_evidence_mutation();

CREATE TRIGGER comment_moderation_decisions_immutable
BEFORE UPDATE OR DELETE ON social.comment_moderation_decisions
FOR EACH ROW EXECUTE FUNCTION social.reject_comment_moderation_evidence_mutation();

INSERT INTO authz.permissions (
    action,
    description,
    risk_level,
    relationship,
    credential_audience,
    grantable,
    discoverable
) VALUES
    (
        'comment.report.create.self',
        '举报一条他人可见评论',
        'low',
        'self',
        'web-session',
        true,
        true
    ),
    (
        'social.report.read',
        '读取脱敏评论举报审核队列',
        'medium',
        'none',
        'staff-session',
        true,
        true
    ),
    (
        'social.report.resolve',
        '关闭举报案件或隐藏违规评论',
        'high',
        'none',
        'staff-session',
        true,
        true
    );

INSERT INTO authz.roles (id, name, description, assignable) VALUES (
    'community_moderator',
    '社区内容审核员',
    '只读取评论举报案件，并作出关闭或隐藏评论的有界决定。',
    true
);

INSERT INTO authz.role_permissions (role_id, action) VALUES
    ('member', 'comment.report.create.self'),
    ('community_moderator', 'social.report.read'),
    ('community_moderator', 'social.report.resolve');

-- +goose Down

DELETE FROM authz.grants WHERE role_id = 'community_moderator';
DELETE FROM authz.role_permissions
WHERE (role_id = 'member' AND action = 'comment.report.create.self')
   OR role_id = 'community_moderator';
DELETE FROM authz.roles WHERE id = 'community_moderator';
DELETE FROM authz.permissions
WHERE action IN (
    'comment.report.create.self',
    'social.report.read',
    'social.report.resolve'
);

DROP TRIGGER IF EXISTS comment_moderation_decisions_immutable ON social.comment_moderation_decisions;
DROP TRIGGER IF EXISTS comment_reports_immutable ON social.comment_reports;
DROP FUNCTION IF EXISTS social.reject_comment_moderation_evidence_mutation();
DROP TRIGGER IF EXISTS comment_moderation_case_protected ON social.comment_moderation_cases;
DROP FUNCTION IF EXISTS social.protect_comment_moderation_case();
DROP TABLE IF EXISTS social.comment_moderation_decisions;
DROP TABLE IF EXISTS social.comment_reports;
DROP TABLE IF EXISTS social.comment_moderation_cases;
