-- +goose Up

-- Social posts are a small, independently versioned aggregate. The first
-- release intentionally stores public plain text only; media, follows, likes,
-- tips and ranking must arrive as separate reviewed capabilities instead of
-- being implied by nullable columns that no use case owns.
CREATE TABLE social.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    author_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    create_request_id uuid NOT NULL,
    create_body_sha256 bytea NOT NULL
        CHECK (octet_length(create_body_sha256) = 32),
    body text NOT NULL,
    body_format text NOT NULL DEFAULT 'plain_text'
        CHECK (body_format = 'plain_text'),
    state text NOT NULL DEFAULT 'visible'
        CHECK (state IN ('visible', 'author_deleted')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    edited_at timestamptz,
    deleted_at timestamptz,
    UNIQUE (author_id, create_request_id),
    CHECK (char_length(body) <= 2000),
    CHECK (
        (state = 'visible' AND char_length(btrim(body)) BETWEEN 1 AND 2000 AND deleted_at IS NULL)
        OR
        (state = 'author_deleted' AND body = '' AND deleted_at IS NOT NULL)
    ),
    CHECK (updated_at >= created_at),
    CHECK (edited_at IS NULL OR (edited_at >= created_at AND edited_at <= updated_at)),
    CHECK (deleted_at IS NULL OR (deleted_at >= created_at AND deleted_at <= updated_at))
);

CREATE INDEX social_posts_visible_feed_idx
    ON social.posts (created_at DESC, id DESC)
    WHERE state = 'visible';

CREATE INDEX social_posts_author_recent_idx
    ON social.posts (author_id, created_at DESC, id DESC);

-- Revisions retain the previous visible body for governance and lost-response
-- diagnosis. They are internal evidence and never cross the public API.
CREATE TABLE social.post_revisions (
    post_id bigint NOT NULL
        REFERENCES social.posts (id) ON DELETE RESTRICT,
    version bigint NOT NULL CHECK (version > 0),
    body text NOT NULL CHECK (char_length(btrim(body)) BETWEEN 1 AND 2000),
    reason text NOT NULL CHECK (reason IN ('author_edit', 'author_delete')),
    editor_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (post_id, version)
);

-- +goose StatementBegin
CREATE FUNCTION social.protect_post_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'social posts must be tombstoned, not deleted';
    END IF;
    IF OLD.id IS DISTINCT FROM NEW.id
        OR OLD.public_id IS DISTINCT FROM NEW.public_id
        OR OLD.author_id IS DISTINCT FROM NEW.author_id
        OR OLD.create_request_id IS DISTINCT FROM NEW.create_request_id
        OR OLD.create_body_sha256 IS DISTINCT FROM NEW.create_body_sha256
        OR OLD.body_format IS DISTINCT FROM NEW.body_format
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'social post identity is immutable';
    END IF;
    IF OLD.state <> 'visible'
        OR NEW.version <> OLD.version + 1
        OR NEW.updated_at < OLD.updated_at THEN
        RAISE EXCEPTION 'social post transition is invalid';
    END IF;
    IF NEW.state = 'visible' THEN
        IF NEW.body IS NOT DISTINCT FROM OLD.body
            OR NEW.edited_at IS DISTINCT FROM NEW.updated_at
            OR NEW.deleted_at IS NOT NULL THEN
            RAISE EXCEPTION 'visible social post update must be a body edit';
        END IF;
    ELSIF NEW.state = 'author_deleted' THEN
        IF NEW.body <> ''
            OR NEW.deleted_at IS DISTINCT FROM NEW.updated_at
            OR NEW.edited_at IS DISTINCT FROM OLD.edited_at THEN
            RAISE EXCEPTION 'social post deletion must create a terminal tombstone';
        END IF;
    ELSE
        RAISE EXCEPTION 'invalid social post state transition';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER social_post_history_protected
BEFORE UPDATE OR DELETE ON social.posts
FOR EACH ROW EXECUTE FUNCTION social.protect_post_history();

-- +goose StatementBegin
CREATE FUNCTION social.reject_post_revision_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'social post revisions are immutable';
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER social_post_revisions_immutable
BEFORE UPDATE OR DELETE ON social.post_revisions
FOR EACH ROW EXECUTE FUNCTION social.reject_post_revision_mutation();

ALTER TABLE social.comment_threads
    DROP CONSTRAINT comment_threads_target_kind_check,
    ADD CONSTRAINT comment_threads_target_kind_check
        CHECK (target_kind IN ('torrent', 'announcement', 'post'));

-- Posts use the same typed-binding comment architecture as torrents and
-- announcements. The shared projection is polymorphic; persisted ownership is
-- still enforced by this real foreign key.
CREATE TABLE social.post_comment_threads (
    thread_id bigint PRIMARY KEY,
    target_kind text NOT NULL DEFAULT 'post' CHECK (target_kind = 'post'),
    post_id bigint NOT NULL UNIQUE
        REFERENCES social.posts (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL,
    FOREIGN KEY (thread_id, target_kind)
        REFERENCES social.comment_threads (id, target_kind) ON DELETE RESTRICT
);

DROP VIEW social.comment_target_projection;

CREATE VIEW social.comment_target_projection AS
SELECT
    binding.thread_id,
    'torrent'::text AS target_kind,
    torrent.public_id::text AS target_key,
    torrent.title AS target_title,
    (torrent.state = 'published') AS target_is_public
FROM torrents.torrents AS torrent
LEFT JOIN social.torrent_comment_threads AS binding
    ON binding.torrent_id = torrent.id
UNION ALL
SELECT
    binding.thread_id,
    'announcement'::text AS target_kind,
    announcement.id AS target_key,
    COALESCE(
        CASE
            WHEN announcement.scheduled_for <= CURRENT_TIMESTAMP
                THEN scheduled_revision.title
            ELSE published_revision.title
        END,
        scheduled_revision.title,
        published_revision.title,
        draft_revision.title
    ) AS target_title,
    (
        announcement.withdrawn_at IS NULL
        AND CASE
            WHEN announcement.scheduled_for <= CURRENT_TIMESTAMP
                THEN announcement.scheduled_revision_id IS NOT NULL
            ELSE announcement.published_revision_id IS NOT NULL
        END
    ) AS target_is_public
FROM catalog.announcements AS announcement
LEFT JOIN catalog.announcement_revisions AS published_revision
    ON published_revision.id = announcement.published_revision_id
LEFT JOIN catalog.announcement_revisions AS scheduled_revision
    ON scheduled_revision.id = announcement.scheduled_revision_id
LEFT JOIN catalog.announcement_revisions AS draft_revision
    ON draft_revision.id = announcement.draft_revision_id
LEFT JOIN social.announcement_comment_threads AS binding
    ON binding.announcement_id = announcement.id
UNION ALL
SELECT
    binding.thread_id,
    'post'::text AS target_kind,
    post.public_id::text AS target_key,
    left(post.body, 160) AS target_title,
    (post.state = 'visible') AS target_is_public
FROM social.posts AS post
LEFT JOIN social.post_comment_threads AS binding
    ON binding.post_id = post.id;

-- Moderation evidence mirrors the typed target binding. Existing torrent and
-- announcement decisions are backfilled unchanged; new post decisions must
-- carry exactly one post UUID.
ALTER TABLE social.comment_moderation_decisions
    DROP CONSTRAINT comment_moderation_decisions_target_identity_check,
    DROP CONSTRAINT comment_moderation_decisions_target_kind_check,
    ADD COLUMN post_public_id uuid,
    ADD CONSTRAINT comment_moderation_decisions_target_kind_check
        CHECK (target_kind IN ('torrent', 'announcement', 'post')),
    ADD CONSTRAINT comment_moderation_decisions_target_identity_check
        CHECK (
            (target_kind = 'torrent'
                AND torrent_public_id IS NOT NULL
                AND announcement_id IS NULL
                AND post_public_id IS NULL)
            OR
            (target_kind = 'announcement'
                AND torrent_public_id IS NULL
                AND announcement_id IS NOT NULL
                AND post_public_id IS NULL)
            OR
            (target_kind = 'post'
                AND torrent_public_id IS NULL
                AND announcement_id IS NULL
                AND post_public_id IS NOT NULL)
        ),
    ADD CONSTRAINT comment_moderation_decisions_post_fk
        FOREIGN KEY (post_public_id)
        REFERENCES social.posts (public_id) ON DELETE RESTRICT;

INSERT INTO authz.permissions (
    action,
    description,
    risk_level,
    relationship,
    credential_audience,
    grantable,
    discoverable
) VALUES
    ('social.post.comment.create.self', '在可见动态下发表评论', 'low', 'self', 'web-session', true, true),
    ('social.post.create.self', '发布公开纯文本动态', 'low', 'self', 'web-session', true, true),
    ('social.post.delete.self', '删除自己的动态', 'low', 'self', 'web-session', true, true),
    ('social.post.read', '读取公开动态圈', 'low', 'none', 'web-session', true, true),
    ('social.post.update.self', '编辑自己的动态', 'low', 'self', 'web-session', true, true);

INSERT INTO authz.role_permissions (role_id, action) VALUES
    ('member', 'social.post.comment.create.self'),
    ('member', 'social.post.create.self'),
    ('member', 'social.post.delete.self'),
    ('member', 'social.post.read'),
    ('member', 'social.post.update.self');

-- +goose Down

DELETE FROM authz.role_permissions
WHERE role_id = 'member'
  AND action IN (
      'social.post.comment.create.self',
      'social.post.create.self',
      'social.post.delete.self',
      'social.post.read',
      'social.post.update.self'
  );

DELETE FROM authz.permissions
WHERE action IN (
    'social.post.comment.create.self',
    'social.post.create.self',
    'social.post.delete.self',
    'social.post.read',
    'social.post.update.self'
);

ALTER TABLE social.comment_moderation_decisions
    DROP CONSTRAINT comment_moderation_decisions_post_fk,
    DROP CONSTRAINT comment_moderation_decisions_target_identity_check,
    DROP CONSTRAINT comment_moderation_decisions_target_kind_check,
    DROP COLUMN post_public_id,
    ADD CONSTRAINT comment_moderation_decisions_target_kind_check
        CHECK (target_kind IN ('torrent', 'announcement')),
    ADD CONSTRAINT comment_moderation_decisions_target_identity_check
        CHECK (
            (target_kind = 'torrent'
                AND torrent_public_id IS NOT NULL
                AND announcement_id IS NULL)
            OR
            (target_kind = 'announcement'
                AND torrent_public_id IS NULL
                AND announcement_id IS NOT NULL)
        );

DROP VIEW social.comment_target_projection;
DROP TABLE social.post_comment_threads;

-- Populated post discussions intentionally make the target-kind rollback fail
-- instead of silently orphaning comment history.
DELETE FROM social.comment_threads AS thread
WHERE thread.target_kind = 'post'
  AND NOT EXISTS (
      SELECT 1
      FROM social.comments AS comment
      WHERE comment.thread_id = thread.id
  );

ALTER TABLE social.comment_threads
    DROP CONSTRAINT comment_threads_target_kind_check,
    ADD CONSTRAINT comment_threads_target_kind_check
        CHECK (target_kind IN ('torrent', 'announcement'));

DROP TRIGGER social_post_revisions_immutable ON social.post_revisions;
DROP FUNCTION social.reject_post_revision_mutation();
DROP TRIGGER social_post_history_protected ON social.posts;
DROP FUNCTION social.protect_post_history();
DROP TABLE social.post_revisions;
DROP TABLE social.posts;

CREATE VIEW social.comment_target_projection AS
SELECT
    binding.thread_id,
    'torrent'::text AS target_kind,
    torrent.public_id::text AS target_key,
    torrent.title AS target_title,
    (torrent.state = 'published') AS target_is_public
FROM torrents.torrents AS torrent
LEFT JOIN social.torrent_comment_threads AS binding
    ON binding.torrent_id = torrent.id
UNION ALL
SELECT
    binding.thread_id,
    'announcement'::text AS target_kind,
    announcement.id AS target_key,
    COALESCE(
        CASE
            WHEN announcement.scheduled_for <= CURRENT_TIMESTAMP
                THEN scheduled_revision.title
            ELSE published_revision.title
        END,
        scheduled_revision.title,
        published_revision.title,
        draft_revision.title
    ) AS target_title,
    (
        announcement.withdrawn_at IS NULL
        AND CASE
            WHEN announcement.scheduled_for <= CURRENT_TIMESTAMP
                THEN announcement.scheduled_revision_id IS NOT NULL
            ELSE announcement.published_revision_id IS NOT NULL
        END
    ) AS target_is_public
FROM catalog.announcements AS announcement
LEFT JOIN catalog.announcement_revisions AS published_revision
    ON published_revision.id = announcement.published_revision_id
LEFT JOIN catalog.announcement_revisions AS scheduled_revision
    ON scheduled_revision.id = announcement.scheduled_revision_id
LEFT JOIN catalog.announcement_revisions AS draft_revision
    ON draft_revision.id = announcement.draft_revision_id
LEFT JOIN social.announcement_comment_threads AS binding
    ON binding.announcement_id = announcement.id;
