-- +goose Up

-- Torrent reports are moderation evidence, not a shortcut around the normal
-- purchase-refund or owner-withdrawal workflows. Reports against the same
-- currently published torrent are aggregated into one open case. A confirmed
-- violation may only disable the torrent; original objects, purchases and
-- accounting records remain intact for later explicit handling.
INSERT INTO authz.permissions (
    action, description, risk_level, relationship, credential_audience,
    grantable, discoverable
) VALUES
    ('torrent.report.create.self', '举报一条他人已发布的种子', 'low', 'self', 'web-session', true, true),
    ('torrent.report.review', '审核种子举报并执行有界下架', 'high', 'none', 'staff-session', true, true);

INSERT INTO authz.role_permissions (role_id, action) VALUES
    ('member', 'torrent.report.create.self'),
    ('site_admin', 'torrent.report.review');

CREATE TABLE torrents.torrent_report_cases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    torrent_id bigint NOT NULL
        REFERENCES torrents.torrents (id) ON DELETE RESTRICT,
    uploader_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    torrent_title text NOT NULL
        CHECK (char_length(btrim(torrent_title)) BETWEEN 1 AND 240),
    state text NOT NULL DEFAULT 'open'
        CHECK (state IN ('open', 'dismissed', 'torrent_disabled')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    opened_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    resolved_at timestamptz,
    CHECK (updated_at >= opened_at),
    CHECK (
        (state = 'open' AND resolved_at IS NULL)
        OR (state <> 'open' AND resolved_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX torrent_report_cases_one_open_per_torrent_idx
    ON torrents.torrent_report_cases (torrent_id)
    WHERE state = 'open';

CREATE INDEX torrent_report_cases_staff_queue_idx
    ON torrents.torrent_report_cases (state, opened_at, id);

-- Reporter identity stays in Core for duplicate and conflict-of-interest
-- checks, but is intentionally excluded from the staff projection.
CREATE TABLE torrents.torrent_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    case_id bigint NOT NULL
        REFERENCES torrents.torrent_report_cases (id) ON DELETE RESTRICT,
    reporter_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    create_request_id uuid NOT NULL,
    create_input_sha256 bytea NOT NULL
        CHECK (octet_length(create_input_sha256) = 32),
    reason_code text NOT NULL CHECK (
        reason_code IN (
            'content_mismatch',
            'copyright',
            'duplicate_or_spam',
            'malicious',
            'other'
        )
    ),
    details text NOT NULL DEFAULT ''
        CHECK (char_length(details) <= 1000),
    created_at timestamptz NOT NULL,
    UNIQUE (reporter_id, create_request_id),
    UNIQUE (case_id, reporter_id),
    CHECK (reason_code <> 'other' OR char_length(btrim(details)) BETWEEN 10 AND 1000)
);

CREATE INDEX torrent_reports_case_chronological_idx
    ON torrents.torrent_reports (case_id, created_at, id);

-- One immutable decision closes a case. Dismissal leaves the current torrent
-- state and version untouched. A confirmed violation performs exactly one
-- published -> disabled transition; hard deletion and refunds remain separate.
CREATE TABLE torrents.torrent_report_decisions (
    id uuid PRIMARY KEY,
    case_id bigint NOT NULL UNIQUE
        REFERENCES torrents.torrent_report_cases (id) ON DELETE RESTRICT,
    case_public_id uuid NOT NULL,
    torrent_id bigint NOT NULL
        REFERENCES torrents.torrents (id) ON DELETE RESTRICT,
    reviewer_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    decision text NOT NULL CHECK (decision IN ('dismiss', 'disable_torrent')),
    reason_code text NOT NULL CHECK (
        reason_code IN (
            'no_violation',
            'content_mismatch',
            'copyright',
            'duplicate_or_spam',
            'malicious',
            'other'
        )
    ),
    note text NOT NULL CHECK (char_length(btrim(note)) BETWEEN 10 AND 1000),
    expected_case_version bigint NOT NULL CHECK (expected_case_version > 0),
    resulting_case_version bigint NOT NULL
        CHECK (resulting_case_version = expected_case_version + 1),
    expected_torrent_state text NOT NULL
        CHECK (expected_torrent_state IN ('pending_review', 'published', 'rejected', 'disabled', 'deleted')),
    resulting_torrent_state text NOT NULL
        CHECK (resulting_torrent_state IN ('pending_review', 'published', 'rejected', 'disabled', 'deleted')),
    expected_torrent_version bigint NOT NULL CHECK (expected_torrent_version > 0),
    resulting_torrent_version bigint NOT NULL CHECK (resulting_torrent_version > 0),
    resulting_case_state text NOT NULL
        CHECK (resulting_case_state IN ('dismissed', 'torrent_disabled')),
    authorization_decision_id uuid NOT NULL,
    decided_at timestamptz NOT NULL,
    CHECK (
        (
            decision = 'dismiss'
            AND reason_code = 'no_violation'
            AND resulting_case_state = 'dismissed'
            AND resulting_torrent_state = expected_torrent_state
            AND resulting_torrent_version = expected_torrent_version
        )
        OR
        (
            decision = 'disable_torrent'
            AND reason_code <> 'no_violation'
            AND resulting_case_state = 'torrent_disabled'
            AND expected_torrent_state = 'published'
            AND resulting_torrent_state = 'disabled'
            AND resulting_torrent_version = expected_torrent_version + 1
        )
    )
);

-- +goose StatementBegin
CREATE FUNCTION torrents.protect_torrent_report_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'torrent report cases cannot be deleted';
    END IF;
    IF OLD.id IS DISTINCT FROM NEW.id
        OR OLD.public_id IS DISTINCT FROM NEW.public_id
        OR OLD.torrent_id IS DISTINCT FROM NEW.torrent_id
        OR OLD.uploader_id IS DISTINCT FROM NEW.uploader_id
        OR OLD.torrent_title IS DISTINCT FROM NEW.torrent_title
        OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'torrent report case identity is immutable';
    END IF;
    IF OLD.state <> 'open'
        OR NEW.state NOT IN ('dismissed', 'torrent_disabled')
        OR NEW.version <> OLD.version + 1
        OR NEW.updated_at < OLD.updated_at
        OR NEW.resolved_at IS DISTINCT FROM NEW.updated_at THEN
        RAISE EXCEPTION 'torrent report case transition is invalid';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER torrent_report_case_guard
BEFORE UPDATE OR DELETE ON torrents.torrent_report_cases
FOR EACH ROW EXECUTE FUNCTION torrents.protect_torrent_report_case();

CREATE TRIGGER torrent_reports_immutable
BEFORE UPDATE OR DELETE ON torrents.torrent_reports
FOR EACH ROW EXECUTE FUNCTION torrents.reject_immutable_evidence_mutation();

CREATE TRIGGER torrent_report_decisions_immutable
BEFORE UPDATE OR DELETE ON torrents.torrent_report_decisions
FOR EACH ROW EXECUTE FUNCTION torrents.reject_immutable_evidence_mutation();

-- +goose Down

DROP TRIGGER torrent_report_decisions_immutable
    ON torrents.torrent_report_decisions;
DROP TRIGGER torrent_reports_immutable
    ON torrents.torrent_reports;
DROP TRIGGER torrent_report_case_guard
    ON torrents.torrent_report_cases;
DROP FUNCTION torrents.protect_torrent_report_case();
DROP TABLE torrents.torrent_report_decisions;
DROP TABLE torrents.torrent_reports;
DROP TABLE torrents.torrent_report_cases;

DELETE FROM authz.role_permissions
WHERE (role_id = 'member' AND action = 'torrent.report.create.self')
   OR (role_id = 'site_admin' AND action = 'torrent.report.review');
DELETE FROM authz.permissions
WHERE action IN ('torrent.report.create.self', 'torrent.report.review');
