-- +goose Up

CREATE SCHEMA IF NOT EXISTS torrents;

-- The original upload is an immutable evidence object. It is inserted only
-- after object storage has acknowledged the exact SHA-256/length pair; download
-- copies may rewrite outer announce fields but never update this row or object.
CREATE TABLE torrents.torrent_objects (
    id uuid PRIMARY KEY,
    content_sha256 bytea NOT NULL UNIQUE
        CHECK (octet_length(content_sha256) = 32),
    byte_length bigint NOT NULL CHECK (byte_length > 0),
    storage_key text NOT NULL UNIQUE
        CHECK (char_length(storage_key) BETWEEN 1 AND 1024),
    parser_version text NOT NULL
        CHECK (parser_version ~ '^[a-z0-9][a-z0-9._-]{0,63}$'),
    validation_profile text NOT NULL
        CHECK (validation_profile IN ('strict_upload', 'legacy_import')),
    compatibility_flags text[] NOT NULL DEFAULT ARRAY[]::text[]
        CHECK (cardinality(compatibility_flags) <= 16),
    info_offset bigint NOT NULL CHECK (info_offset >= 0),
    info_length bigint NOT NULL CHECK (info_length > 0),
    created_at timestamptz NOT NULL,
    CHECK (info_offset <= byte_length - info_length)
);

-- This is the write-side source of truth. catalog.torrents remains a temporary
-- public demo/read projection until a projector is connected; Tracker will
-- consume a separate published-infohash allowlist projection and must never
-- query this table during announce.
CREATE TABLE torrents.torrents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    public_id uuid NOT NULL UNIQUE,
    uploader_id uuid NOT NULL
        REFERENCES identity.users (id) ON DELETE RESTRICT,
    category_id text NOT NULL
        REFERENCES catalog.categories (id) ON DELETE RESTRICT,
    object_id uuid NOT NULL UNIQUE
        REFERENCES torrents.torrent_objects (id) ON DELETE RESTRICT,
    info_hash_v1 bytea NOT NULL UNIQUE
        CHECK (octet_length(info_hash_v1) = 20),
    content_name text NOT NULL
        CHECK (char_length(content_name) BETWEEN 1 AND 255),
    title text NOT NULL
        CHECK (char_length(btrim(title)) BETWEEN 1 AND 240),
    subtitle text NOT NULL DEFAULT ''
        CHECK (char_length(subtitle) <= 300),
    total_size_bytes bigint NOT NULL CHECK (total_size_bytes > 0),
    payload_size_bytes bigint NOT NULL CHECK (
        payload_size_bytes > 0 AND payload_size_bytes <= total_size_bytes
    ),
    file_count integer NOT NULL CHECK (file_count BETWEEN 1 AND 100000),
    padding_file_count integer NOT NULL DEFAULT 0 CHECK (
        padding_file_count >= 0 AND padding_file_count <= file_count
    ),
    piece_length_bytes bigint NOT NULL CHECK (piece_length_bytes > 0),
    piece_count integer NOT NULL CHECK (piece_count > 0),
    state text NOT NULL DEFAULT 'pending_review' CHECK (
        state IN ('pending_review', 'published', 'rejected', 'disabled', 'deleted')
    ),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    submitted_at timestamptz NOT NULL,
    published_at timestamptz,
    state_changed_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK (state NOT IN ('published', 'disabled') OR published_at IS NOT NULL),
    CHECK (state NOT IN ('pending_review', 'rejected') OR published_at IS NULL),
    CHECK (published_at IS NULL OR published_at >= submitted_at),
    CHECK (state_changed_at >= submitted_at),
    CHECK (updated_at >= state_changed_at)
);

CREATE INDEX torrents_latest_published_idx
    ON torrents.torrents (published_at DESC, id DESC)
    WHERE state = 'published';

CREATE INDEX torrents_pending_review_idx
    ON torrents.torrents (submitted_at, id)
    WHERE state = 'pending_review';

CREATE INDEX torrents_uploader_history_idx
    ON torrents.torrents (uploader_id, submitted_at DESC, id DESC);

-- File paths remain componentized to avoid losing path boundaries during
-- migration. display_path is a deterministic read projection; extraction code
-- must still join components beneath a sandbox root rather than trusting it as
-- a host path.
CREATE TABLE torrents.torrent_files (
    torrent_id bigint NOT NULL
        REFERENCES torrents.torrents (id) ON DELETE RESTRICT,
    file_index integer NOT NULL CHECK (file_index BETWEEN 0 AND 99999),
    path_components text[] NOT NULL CHECK (
        cardinality(path_components) BETWEEN 1 AND 64
        AND array_position(path_components, NULL) IS NULL
    ),
    display_path text NOT NULL
        CHECK (char_length(display_path) BETWEEN 1 AND 4096),
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    is_padding boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (torrent_id, file_index),
    UNIQUE (torrent_id, display_path)
);

-- Runtime repositories have no update/delete methods for object evidence, but
-- the database also rejects accidental ad-hoc mutations. Production still uses
-- a non-owner application role; this trigger is the invariant backstop rather
-- than the sole privilege boundary.
-- +goose StatementBegin
CREATE FUNCTION torrents.reject_immutable_evidence_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% evidence is immutable', TG_TABLE_NAME;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER torrent_objects_immutable
BEFORE UPDATE OR DELETE ON torrents.torrent_objects
FOR EACH ROW EXECUTE FUNCTION torrents.reject_immutable_evidence_mutation();

CREATE TRIGGER torrent_files_immutable
BEFORE UPDATE OR DELETE ON torrents.torrent_files
FOR EACH ROW EXECUTE FUNCTION torrents.reject_immutable_evidence_mutation();

-- Metadata and review state may evolve, while the fields derived from original
-- info bytes cannot. Deletion is represented by a terminal tombstone state so
-- Tracker revocation, audit, and old-client diagnostics retain the same ID.
-- +goose StatementBegin
CREATE FUNCTION torrents.protect_torrent_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'torrent aggregates must be tombstoned, not deleted';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
        OR OLD.public_id IS DISTINCT FROM NEW.public_id
        OR OLD.uploader_id IS DISTINCT FROM NEW.uploader_id
        OR OLD.object_id IS DISTINCT FROM NEW.object_id
        OR OLD.info_hash_v1 IS DISTINCT FROM NEW.info_hash_v1
        OR OLD.content_name IS DISTINCT FROM NEW.content_name
        OR OLD.total_size_bytes IS DISTINCT FROM NEW.total_size_bytes
        OR OLD.payload_size_bytes IS DISTINCT FROM NEW.payload_size_bytes
        OR OLD.file_count IS DISTINCT FROM NEW.file_count
        OR OLD.padding_file_count IS DISTINCT FROM NEW.padding_file_count
        OR OLD.piece_length_bytes IS DISTINCT FROM NEW.piece_length_bytes
        OR OLD.piece_count IS DISTINCT FROM NEW.piece_count
        OR OLD.submitted_at IS DISTINCT FROM NEW.submitted_at THEN
        RAISE EXCEPTION 'torrent swarm identity is immutable';
    END IF;

    IF NEW.version <> OLD.version + 1 THEN
        RAISE EXCEPTION 'torrent aggregate version must increment exactly once';
    END IF;

    IF NEW.updated_at < OLD.updated_at THEN
        RAISE EXCEPTION 'torrent update time cannot move backwards';
    END IF;

    IF OLD.state IS NOT DISTINCT FROM NEW.state THEN
        IF OLD.state_changed_at IS DISTINCT FROM NEW.state_changed_at
            OR OLD.published_at IS DISTINCT FROM NEW.published_at THEN
            RAISE EXCEPTION 'unchanged torrent state cannot rewrite transition times';
        END IF;
        RETURN NEW;
    END IF;

    IF NOT (
        (OLD.state = 'pending_review' AND NEW.state IN ('published', 'rejected', 'deleted'))
        OR (OLD.state = 'published' AND NEW.state IN ('disabled', 'deleted'))
        OR (OLD.state = 'rejected' AND NEW.state IN ('pending_review', 'deleted'))
        OR (OLD.state = 'disabled' AND NEW.state IN ('published', 'deleted'))
    ) THEN
        RAISE EXCEPTION 'torrent state transition from % to % is invalid', OLD.state, NEW.state;
    END IF;

    IF NEW.state_changed_at < OLD.state_changed_at THEN
        RAISE EXCEPTION 'torrent state time cannot move backwards';
    END IF;

    IF OLD.published_at IS NOT NULL
        AND OLD.published_at IS DISTINCT FROM NEW.published_at THEN
        RAISE EXCEPTION 'torrent first publication time is immutable';
    END IF;

    IF OLD.published_at IS NULL AND NEW.state = 'published'
        AND NEW.published_at IS DISTINCT FROM NEW.state_changed_at THEN
        RAISE EXCEPTION 'first publication time must equal its state transition time';
    END IF;

    IF OLD.published_at IS NULL AND NEW.state <> 'published'
        AND NEW.published_at IS NOT NULL THEN
        RAISE EXCEPTION 'publication time cannot appear outside publication';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER torrent_identity_immutable
BEFORE UPDATE OR DELETE ON torrents.torrents
FOR EACH ROW EXECUTE FUNCTION torrents.protect_torrent_identity();

-- +goose Down
DROP SCHEMA IF EXISTS torrents CASCADE;
