// Package torrents owns immutable metainfo identity, torrent submission state,
// and the Core-side source of truth from which catalog and Tracker projections
// are produced.
package torrents

import (
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/google/uuid"

	"github.com/peergo/peergo/services/core/internal/contracts/objectstorage"
)

const (
	// ParserVersion is persisted beside every immutable object. Changing parser
	// behavior requires a new value so imports and later reparses remain
	// reproducible instead of silently changing historical interpretation.
	ParserVersion = "peergo-metainfo-v1"
	// ParserVersionLegacyHybridV1V2 identifies the migration-only parser view
	// which validates and materializes the complete BEP 3 half of a BEP 52
	// hybrid object. New uploads cannot select this parser path.
	ParserVersionLegacyHybridV1V2 = "peergo-metainfo-hybrid-v1-view-v1"

	maxTorrentTitleRunes       = 240
	maxTorrentSubtitleRunes    = 300
	maxTorrentDescriptionBytes = 4 * 1024 * 1024
	maxTorrentMediaInfoBytes   = 16 * 1024 * 1024
)

var (
	imdbExternalIDPattern    = regexp.MustCompile(`^tt[0-9]{7,10}$`)
	numericExternalIDPattern = regexp.MustCompile(`^[0-9]{1,20}$`)
	facetStableIDPattern     = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,63}$`)
)

var (
	ErrTorrentInputInvalid      = errors.New("torrent input is invalid")
	ErrTorrentMetadataUnchanged = errors.New("torrent editable metadata is unchanged")
	ErrTorrentStateConflict     = errors.New("torrent state transition is invalid")
	ErrTorrentTimeRegression    = errors.New("torrent state time moved backwards")
)

// TorrentID is the stable numeric identity used by migration and Tracker
// contracts. PostgreSQL GENERATED BY DEFAULT permits preserving positive PtYes
// IDs while still allocating IDs for newly submitted torrents.
type TorrentID int64

// InfoHashV1 is the protocol identity: SHA-1 over the exact bencoded info value
// found in the uploaded object. SHA-1 is retained here only because BEP 3
// defines the wire identity; it is never used as a security digest.
type InfoHashV1 [20]byte

func (hash InfoHashV1) Hex() string {
	return hex.EncodeToString(hash[:])
}

// ParseInfoHashV1Hex converts legacy hexadecimal database values at the import
// boundary. Core storage and internal contracts retain the fixed 20-byte form.
func ParseInfoHashV1Hex(value string) (InfoHashV1, error) {
	decoded, err := hex.DecodeString(strings.TrimSpace(value))
	if err != nil || len(decoded) != len(InfoHashV1{}) {
		return InfoHashV1{}, fmt.Errorf("parse v1 info hash: %w", ErrTorrentInputInvalid)
	}
	var result InfoHashV1
	copy(result[:], decoded)
	return result, nil
}

// ObjectSHA256 identifies the complete immutable .torrent object independently
// from its protocol info hash. It is used for storage verification and import
// reconciliation, not announce requests.
type ObjectSHA256 = objectstorage.SHA256

// State separates review and availability semantics. There is deliberately no
// editable tracker_allowed boolean: Tracker eligibility is derived from the
// published state and delivered through a reliable projection later.
type State string

const (
	StatePendingReview State = "pending_review"
	StatePublished     State = "published"
	StateRejected      State = "rejected"
	StateDisabled      State = "disabled"
	StateDeleted       State = "deleted"
)

// TorrentObject is the persisted identity of the original uploaded bytes.
// Announce URLs may be rewritten only in a generated download copy; this object
// and its info span must never be edited in place.
type TorrentObject struct {
	ID                 uuid.UUID
	ContentSHA256      ObjectSHA256
	ByteLength         int64
	ParserVersion      string
	ValidationProfile  ValidationProfile
	CompatibilityFlags []CompatibilityFlag
	InfoOffset         int64
	InfoLength         int64
}

// Torrent is the write-side aggregate. File rows and the original object are
// separate immutable records so ordinary metadata or review updates never
// rewrite the bytes that define the swarm.
type Torrent struct {
	ID                  TorrentID
	UploaderID          uuid.UUID
	CategoryID          string
	Title               string
	Subtitle            string
	Description         string
	DescriptionFormat   string
	MediaInfo           string
	Anonymous           bool
	ExternalIdentifiers []ExternalIdentifier
	FacetSelections     []FacetSelection
	Screenshots         []TorrentScreenshot
	InfoHashV1          InfoHashV1
	Object              TorrentObject
	ContentName         string
	TotalSizeBytes      int64
	PayloadSizeBytes    int64
	FileCount           int
	PaddingFileCount    int
	PieceLengthBytes    int64
	PieceCount          int
	State               State
	Version             int64
	SubmittedAt         time.Time
	PublishedAt         *time.Time
	StateChangedAt      time.Time
	UpdatedAt           time.Time
}

const DescriptionFormatMarkdown = "markdown"

// ExternalIdentifier is shared by upload, migration and public detail reads.
// Provider-specific IDs are persisted instead of arbitrary URLs so renderers
// can construct safe outbound links without storing untrusted destinations.
type ExternalIdentifier struct {
	Provider   string
	ExternalID string
}

// FacetSelection carries stable controlled identifiers only. Labels and the
// canonical single/multi mode stay catalog-owned and are resolved again by
// PostgreSQL during finalization.
type FacetSelection struct {
	FacetID    string
	OptionKeys []string
}

// EditableMetadata is the bounded part of a submission that may be corrected
// without changing the swarm. It deliberately excludes the original object,
// info hash, content name, file tree, sizes and uploader identity.
type EditableMetadata struct {
	CategoryID string
	Title      string
	Subtitle   string
}

// NewEditableMetadata is the single normalization boundary shared by initial
// upload and uploader resubmission. Keeping these rules here prevents the HTTP
// and review modules from growing slightly different title/category limits.
func NewEditableMetadata(categoryID, title, subtitle string) (EditableMetadata, error) {
	metadata := EditableMetadata{
		CategoryID: strings.TrimSpace(categoryID),
		Title:      strings.TrimSpace(title),
		Subtitle:   strings.TrimSpace(subtitle),
	}
	if !metadata.valid() {
		return EditableMetadata{}, ErrTorrentInputInvalid
	}
	return metadata, nil
}

type NewPendingTorrentInput struct {
	UploaderID          uuid.UUID
	CategoryID          string
	Title               string
	Subtitle            string
	Description         string
	MediaInfo           string
	Anonymous           bool
	ExternalIdentifiers []ExternalIdentifier
	FacetSelections     []FacetSelection
	Screenshots         []TorrentScreenshot
	ObjectID            uuid.UUID
	Metainfo            ParsedMetainfo
	OccurredAt          time.Time
}

// NewPendingTorrent creates the only state accepted from the user upload path.
// Publication remains a separate reviewed transition so neither an HTTP
// handler nor an object-store success can accidentally authorize a swarm.
func NewPendingTorrent(input NewPendingTorrentInput) (Torrent, error) {
	metadata, err := NewEditableMetadata(input.CategoryID, input.Title, input.Subtitle)
	if err != nil {
		return Torrent{}, err
	}
	externalIdentifiers, err := normalizeExternalIdentifiers(input.ExternalIdentifiers)
	if err != nil {
		return Torrent{}, ErrTorrentInputInvalid
	}
	facetSelections, err := normalizeFacetSelections(input.FacetSelections)
	if err != nil || !validTorrentContent(input.Description, input.MediaInfo) || !validTorrentScreenshots(input.Screenshots) {
		return Torrent{}, ErrTorrentInputInvalid
	}
	now := input.OccurredAt.UTC()

	if input.UploaderID == uuid.Nil || input.ObjectID == uuid.Nil ||
		now.IsZero() || !validParsedMetainfo(input.Metainfo) {
		return Torrent{}, ErrTorrentInputInvalid
	}

	object := TorrentObject{
		ID:                 input.ObjectID,
		ContentSHA256:      input.Metainfo.ObjectSHA256,
		ByteLength:         input.Metainfo.ObjectByteLength,
		ParserVersion:      input.Metainfo.ParserVersion,
		ValidationProfile:  input.Metainfo.ValidationProfile,
		CompatibilityFlags: append([]CompatibilityFlag(nil), input.Metainfo.CompatibilityFlags...),
		InfoOffset:         input.Metainfo.InfoOffset,
		InfoLength:         input.Metainfo.InfoLength,
	}

	return Torrent{
		UploaderID:          input.UploaderID,
		CategoryID:          metadata.CategoryID,
		Title:               metadata.Title,
		Subtitle:            metadata.Subtitle,
		Description:         input.Description,
		DescriptionFormat:   DescriptionFormatMarkdown,
		MediaInfo:           input.MediaInfo,
		Anonymous:           input.Anonymous,
		ExternalIdentifiers: externalIdentifiers,
		FacetSelections:     facetSelections,
		Screenshots:         append([]TorrentScreenshot(nil), input.Screenshots...),
		InfoHashV1:          input.Metainfo.InfoHashV1,
		Object:              object,
		ContentName:         input.Metainfo.Name,
		TotalSizeBytes:      input.Metainfo.TotalSizeBytes,
		PayloadSizeBytes:    input.Metainfo.PayloadSizeBytes,
		FileCount:           len(input.Metainfo.Files),
		PaddingFileCount:    input.Metainfo.PaddingFileCount,
		PieceLengthBytes:    input.Metainfo.PieceLengthBytes,
		PieceCount:          input.Metainfo.PieceCount,
		State:               StatePendingReview,
		Version:             1,
		SubmittedAt:         now,
		StateChangedAt:      now,
		UpdatedAt:           now,
	}, nil
}

func normalizeFacetSelections(values []FacetSelection) ([]FacetSelection, error) {
	if len(values) > 20 {
		return nil, ErrTorrentInputInvalid
	}
	normalized := make([]FacetSelection, 0, len(values))
	seenFacets := make(map[string]struct{}, len(values))
	for _, value := range values {
		facetID := strings.TrimSpace(value.FacetID)
		if !facetStableIDPattern.MatchString(facetID) || len(value.OptionKeys) < 1 || len(value.OptionKeys) > 32 {
			return nil, ErrTorrentInputInvalid
		}
		if _, duplicate := seenFacets[facetID]; duplicate {
			return nil, ErrTorrentInputInvalid
		}
		seenFacets[facetID] = struct{}{}
		optionKeys := make([]string, 0, len(value.OptionKeys))
		seenOptions := make(map[string]struct{}, len(value.OptionKeys))
		for _, rawOption := range value.OptionKeys {
			optionKey := strings.TrimSpace(rawOption)
			if optionKey != rawOption || optionKey == "" || !utf8.ValidString(optionKey) || utf8.RuneCountInString(optionKey) > 80 {
				return nil, ErrTorrentInputInvalid
			}
			if _, duplicate := seenOptions[optionKey]; duplicate {
				return nil, ErrTorrentInputInvalid
			}
			seenOptions[optionKey] = struct{}{}
			optionKeys = append(optionKeys, optionKey)
		}
		sort.Strings(optionKeys)
		normalized = append(normalized, FacetSelection{FacetID: facetID, OptionKeys: optionKeys})
	}
	sort.Slice(normalized, func(left, right int) bool {
		return normalized[left].FacetID < normalized[right].FacetID
	})
	return normalized, nil
}

func validTorrentContent(description, mediaInfo string) bool {
	return utf8.ValidString(description) && utf8.ValidString(mediaInfo) &&
		len(description) <= maxTorrentDescriptionBytes &&
		len(mediaInfo) <= maxTorrentMediaInfoBytes
}

func normalizeExternalIdentifiers(values []ExternalIdentifier) ([]ExternalIdentifier, error) {
	if len(values) > 5 {
		return nil, ErrTorrentInputInvalid
	}
	normalized := make([]ExternalIdentifier, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		provider := strings.ToLower(strings.TrimSpace(value.Provider))
		externalID := strings.TrimSpace(value.ExternalID)
		valid := provider == "imdb" && imdbExternalIDPattern.MatchString(externalID)
		if provider == "tmdb" || provider == "douban" || provider == "bangumi" || provider == "steam" {
			valid = numericExternalIDPattern.MatchString(externalID)
		}
		if !valid {
			return nil, ErrTorrentInputInvalid
		}
		if _, duplicate := seen[provider]; duplicate {
			return nil, ErrTorrentInputInvalid
		}
		seen[provider] = struct{}{}
		normalized = append(normalized, ExternalIdentifier{Provider: provider, ExternalID: externalID})
	}
	sort.Slice(normalized, func(left, right int) bool {
		return normalized[left].Provider < normalized[right].Provider
	})
	return normalized, nil
}

// Publish makes the torrent visible and eligible for Tracker allowlisting.
func (torrent *Torrent) Publish(occurredAt time.Time) error {
	return torrent.transition(StatePublished, occurredAt)
}

// Reject records a review outcome without deleting the immutable submission.
func (torrent *Torrent) Reject(occurredAt time.Time) error {
	return torrent.transition(StateRejected, occurredAt)
}

// Resubmit returns a rejected object to review. A changed info dictionary must
// instead create a new torrent because it has a different swarm identity.
func (torrent *Torrent) Resubmit(occurredAt time.Time) error {
	return torrent.transition(StatePendingReview, occurredAt)
}

// ResubmitWithMetadata applies the only editable fields and reopens review as
// one aggregate transition. Work is performed on a copy so invalid state/time
// or an unchanged form cannot partially mutate the caller's aggregate.
func (torrent *Torrent) ResubmitWithMetadata(metadata EditableMetadata, occurredAt time.Time) error {
	if torrent == nil || !metadata.valid() {
		return ErrTorrentInputInvalid
	}
	if torrent.CategoryID == metadata.CategoryID && torrent.Title == metadata.Title && torrent.Subtitle == metadata.Subtitle {
		return ErrTorrentMetadataUnchanged
	}

	next := *torrent
	next.CategoryID = metadata.CategoryID
	next.Title = metadata.Title
	next.Subtitle = metadata.Subtitle
	if err := next.Resubmit(occurredAt); err != nil {
		return err
	}
	*torrent = next
	return nil
}

// Disable revokes public and Tracker availability while retaining the record
// needed for client warnings, review evidence, and migration reconciliation.
func (torrent *Torrent) Disable(occurredAt time.Time) error {
	return torrent.transition(StateDisabled, occurredAt)
}

// Restore republishes a previously disabled torrent with the same immutable
// info hash.
func (torrent *Torrent) Restore(occurredAt time.Time) error {
	return torrent.transition(StatePublished, occurredAt)
}

// Delete creates a terminal tombstone. Physical object retention is governed
// separately and must not be coupled to this state change.
func (torrent *Torrent) Delete(occurredAt time.Time) error {
	return torrent.transition(StateDeleted, occurredAt)
}

// TrackerEligible is the single Core-side eligibility rule consumed by the
// future allowlist projector. The Tracker data plane still uses its own local
// projection and never queries this aggregate on announce.
func (torrent Torrent) TrackerEligible() bool {
	return torrent.State == StatePublished
}

func (torrent *Torrent) transition(next State, occurredAt time.Time) error {
	if torrent == nil || !allowedTransition(torrent.State, next) {
		return ErrTorrentStateConflict
	}
	now := occurredAt.UTC()
	if now.IsZero() || now.Before(torrent.SubmittedAt) || now.Before(torrent.StateChangedAt) {
		return ErrTorrentTimeRegression
	}

	if next == StatePublished && torrent.PublishedAt == nil {
		publishedAt := now
		torrent.PublishedAt = &publishedAt
	}
	torrent.State = next
	torrent.Version++
	torrent.StateChangedAt = now
	torrent.UpdatedAt = now
	return nil
}

func allowedTransition(current, next State) bool {
	switch current {
	case StatePendingReview:
		return next == StatePublished || next == StateRejected || next == StateDeleted
	case StatePublished:
		return next == StateDisabled || next == StateDeleted
	case StateRejected:
		return next == StatePendingReview || next == StateDeleted
	case StateDisabled:
		return next == StatePublished || next == StateDeleted
	case StateDeleted:
		return false
	default:
		return false
	}
}

func validTorrentText(value string, minimum, maximum int) bool {
	if !utf8.ValidString(value) {
		return false
	}
	length := utf8.RuneCountInString(value)
	return length >= minimum && length <= maximum
}

func (metadata EditableMetadata) valid() bool {
	return metadata.CategoryID != "" &&
		validTorrentText(metadata.Title, 1, maxTorrentTitleRunes) &&
		validTorrentText(metadata.Subtitle, 0, maxTorrentSubtitleRunes)
}

func validParsedMetainfo(metainfo ParsedMetainfo) bool {
	return metainfo.ParserVersion == ParserVersion && metainfo.ValidationProfile.valid() &&
		metainfo.ObjectByteLength > 0 && metainfo.InfoOffset >= 0 && metainfo.InfoLength > 0 &&
		metainfo.InfoOffset <= metainfo.ObjectByteLength-metainfo.InfoLength && metainfo.Name != "" &&
		metainfo.Private && metainfo.TotalSizeBytes > 0 && metainfo.PayloadSizeBytes > 0 &&
		metainfo.PayloadSizeBytes <= metainfo.TotalSizeBytes && len(metainfo.Files) > 0 &&
		metainfo.PaddingFileCount >= 0 && metainfo.PaddingFileCount <= len(metainfo.Files) &&
		metainfo.PieceLengthBytes > 0 && metainfo.PieceCount > 0
}
